# -*- coding: utf-8 -*-
"""New vocabulary, grouped by body system.

Entry tuple:
(word, ipa, def_en, def_zh, example_en, example_zh, difficulty, [morpheme_keys])
morpheme_keys are alias strings resolved against the combined morpheme table.
Inner Chinese quotation uses full-width 「」 (ASCII " is the Python delimiter).
"""

NEW_VOCAB = {
    # ════════════════ System 1 · Cardiovascular ════════════════
    1: [
        ("angina", "/ænˈdʒaɪnə/", "Chest pain caused by reduced blood flow to the heart muscle.", "心绞痛：因心肌供血减少引起的胸痛。", "Stable angina is typically triggered by exertion and relieved by rest.", "稳定型心绞痛通常由劳累诱发、休息后缓解。", 2, []),
        ("infarction", "/ɪnˈfɑːrkʃən/", "Tissue death (necrosis) caused by a sudden loss of blood supply.", "梗死：因血供突然中断导致的组织坏死。", "A myocardial infarction is commonly known as a heart attack.", "心肌梗死即俗称的心脏病发作。", 3, []),
        ("thrombosis", "/θrɒmˈboʊsɪs/", "The formation of a blood clot (thrombus) inside a blood vessel.", "血栓形成：血管内形成血凝块（血栓）。", "Deep vein thrombosis can occur after long periods of immobility.", "长时间不活动后可能发生深静脉血栓形成。", 3, ["thrombo-", "-osis"]),
        ("embolism", "/ˈembəlɪzəm/", "Blockage of a vessel by a clot or other material carried in the blood.", "栓塞：血液带来的血栓或其他物质阻塞血管。", "A pulmonary embolism blocks an artery in the lungs and is life-threatening.", "肺栓塞阻塞肺部动脉，可危及生命。", 3, []),
        ("aneurysm", "/ˈænjərɪzəm/", "An abnormal bulge in the wall of a weakened artery.", "动脉瘤：动脉壁薄弱处的异常膨出。", "An aortic aneurysm may rupture and cause massive internal bleeding.", "主动脉瘤可能破裂并引起大量内出血。", 3, []),
        ("endocarditis", "/ˌendoʊkɑːrˈdaɪtɪs/", "Inflammation of the inner lining of the heart and its valves.", "心内膜炎：心脏内膜及瓣膜的炎症。", "Bacterial endocarditis can damage heart valves.", "细菌性心内膜炎可损害心脏瓣膜。", 3, ["endo-", "cardio-", "-itis"]),
        ("pericarditis", "/ˌperɪkɑːrˈdaɪtɪs/", "Inflammation of the pericardium, the sac surrounding the heart.", "心包炎：包绕心脏的心包的炎症。", "Pericarditis often causes sharp chest pain that eases when leaning forward.", "心包炎常引起尖锐胸痛，前倾时可减轻。", 3, ["peri-", "cardio-", "-itis"]),
        ("cardiomyopathy", "/ˌkɑːrdioʊmaɪˈɒpəθi/", "Disease of the heart muscle that impairs its ability to pump blood.", "心肌病：损害心脏泵血能力的心肌疾病。", "Dilated cardiomyopathy enlarges and weakens the heart's chambers.", "扩张型心肌病使心腔扩大、收缩力减弱。", 4, ["cardio-", "myo-", "-pathy"]),
        ("hypotension", "/ˌhaɪpoʊˈtenʃən/", "Abnormally low blood pressure.", "低血压：血压异常偏低。", "Severe hypotension can cause dizziness and fainting.", "严重低血压可引起头晕和晕厥。", 2, ["hypo-"]),
        ("palpitation", "/ˌpælpɪˈteɪʃən/", "A sensation of a rapid, strong, or irregular heartbeat.", "心悸：感到心跳过快、过强或不规则。", "She felt palpitations after drinking too much coffee.", "她喝太多咖啡后感到心悸。", 2, []),
        ("fibrillation", "/ˌfɪbrɪˈleɪʃən/", "Rapid, disorganized contraction of heart muscle fibers.", "颤动：心肌纤维快速而无序的收缩。", "Atrial fibrillation increases the risk of stroke.", "心房颤动会增加卒中的风险。", 3, []),
        ("vasodilation", "/ˌveɪzoʊdaɪˈleɪʃən/", "Widening of blood vessels, which lowers blood pressure.", "血管扩张：血管口径增大，使血压下降。", "Vasodilation of skin vessels helps release body heat.", "皮肤血管扩张有助于散发体热。", 3, ["vaso-"]),
        ("vasoconstriction", "/ˌveɪzoʊkənˈstrɪkʃən/", "Narrowing of blood vessels, which raises blood pressure.", "血管收缩：血管口径变窄，使血压升高。", "Cold temperatures cause vasoconstriction to conserve heat.", "寒冷使血管收缩以保存热量。", 3, ["vaso-"]),
        ("hyperlipidemia", "/ˌhaɪpərlɪpɪˈdiːmiə/", "Abnormally high levels of lipids (fats) in the blood.", "高脂血症：血中脂质（脂肪）水平异常升高。", "Hyperlipidemia is a major risk factor for atherosclerosis.", "高脂血症是动脉粥样硬化的主要危险因素。", 3, ["hyper-", "-emia"]),
        ("phlebitis", "/flɪˈbaɪtɪs/", "Inflammation of a vein.", "静脉炎：静脉的炎症。", "Phlebitis in a leg vein causes redness and tenderness.", "腿部静脉炎引起发红和压痛。", 2, ["phlebo-", "-itis"]),
        ("thrombophlebitis", "/ˌθrɒmboʊflɪˈbaɪtɪs/", "Inflammation of a vein associated with a blood clot.", "血栓性静脉炎：伴有血栓的静脉炎症。", "Thrombophlebitis often presents as a painful, swollen vein.", "血栓性静脉炎常表现为疼痛、肿胀的静脉。", 3, ["thrombo-", "phlebo-", "-itis"]),
        ("edema", "/ɪˈdiːmə/", "Swelling caused by excess fluid trapped in body tissues.", "水肿：体液在组织中潴留过多引起的肿胀。", "Heart failure can cause edema in the ankles and legs.", "心力衰竭可引起踝部和腿部水肿。", 2, []),
        ("murmur", "/ˈmɜːrmər/", "An abnormal sound heard during the heartbeat, often from turbulent blood flow.", "心脏杂音：心跳时听到的异常声音，常因血流湍急所致。", "The doctor detected a heart murmur with a stethoscope.", "医生用听诊器发现了心脏杂音。", 2, []),
        ("systole", "/ˈsɪstəli/", "The phase of the heartbeat when the ventricles contract and eject blood.", "收缩期：心室收缩并射出血液的心跳阶段。", "Systolic pressure is measured during systole.", "收缩压是在收缩期测得的。", 3, []),
        ("diastole", "/daɪˈæstəli/", "The phase of the heartbeat when the heart relaxes and fills with blood.", "舒张期：心脏舒张并充盈血液的心跳阶段。", "Diastolic pressure reflects the resistance in the arteries during diastole.", "舒张压反映舒张期动脉中的阻力。", 3, []),
        ("electrocardiogram", "/ɪˌlektroʊˈkɑːrdioʊɡræm/", "A recording of the electrical activity of the heart (ECG/EKG).", "心电图：记录心脏电活动的图形（ECG/EKG）。", "The electrocardiogram showed an irregular rhythm.", "心电图显示节律不齐。", 2, ["cardio-", "-gram"]),
        ("echocardiography", "/ˌekoʊˌkɑːrdiˈɒɡrəfi/", "Imaging of the heart using ultrasound waves.", "超声心动图：用超声波对心脏成像的检查。", "Echocardiography can measure how well the heart pumps.", "超声心动图可评估心脏泵血功能。", 3, ["cardio-"]),
        ("angiography", "/ˌændʒiˈɒɡrəfi/", "Imaging of blood vessels using a contrast dye.", "血管造影：用造影剂对血管成像的检查。", "Coronary angiography revealed a blocked artery.", "冠状动脉造影发现一条动脉阻塞。", 3, ["angio-"]),
        ("coronary", "/ˈkɔːrəneri/", "Relating to the arteries that supply the heart muscle.", "冠状的：与供应心肌的动脉有关。", "The coronary arteries branch from the aorta.", "冠状动脉自主动脉分出。", 2, []),
        ("aorta", "/eɪˈɔːrtə/", "The largest artery, carrying blood from the heart to the body.", "主动脉：人体最大的动脉，将血液从心脏输送到全身。", "The aorta arches over the heart before descending through the chest.", "主动脉在心脏上方形成弓形后下行穿过胸部。", 2, ["aorto-"]),
        ("ventricle", "/ˈventrɪkəl/", "One of the two lower pumping chambers of the heart.", "心室：心脏下部两个泵血腔之一。", "The left ventricle pumps oxygen-rich blood to the body.", "左心室将富氧血泵送至全身。", 2, []),
        ("atrium", "/ˈeɪtriəm/", "One of the two upper receiving chambers of the heart.", "心房：心脏上部两个接收血液的腔之一。", "Blood returning to the heart first enters an atrium.", "回流心脏的血液首先进入心房。", 2, []),
        ("hemostasis", "/ˌhiːmoʊˈsteɪsɪs/", "The process that stops bleeding, including clot formation.", "止血：使出血停止的过程，包括血凝块形成。", "Platelets play a key role in hemostasis.", "血小板在止血中起关键作用。", 3, ["hemo-", "-stasis"]),
        ("anticoagulant", "/ˌæntikoʊˈæɡjələnt/", "A drug that prevents or slows the clotting of blood.", "抗凝剂：预防或减缓血液凝固的药物。", "Patients with atrial fibrillation often take an anticoagulant.", "房颤患者常服用抗凝剂。", 3, ["anti-"]),
        ("tachyarrhythmia", "/ˌtækiəˈrɪðmiə/", "An abnormally fast and irregular heart rhythm.", "快速性心律失常：心率异常增快且不规则。", "The patient's tachyarrhythmia was controlled with medication.", "患者的快速性心律失常通过药物得到控制。", 4, ["tachy-"]),
        ("cardiology", "/ˌkɑːrdiˈɒlədʒi/", "The branch of medicine dealing with the heart.", "心脏病学：研究心脏的医学分支。", "She is training in cardiology to treat heart disease.", "她正在心脏病学专业进修以治疗心脏疾病。", 2, ["cardio-", "-logy"]),
        ("angioma", "/ˌændʒiˈoʊmə/", "A benign tumor made of blood or lymph vessels.", "血管瘤：由血管或淋巴管构成的良性肿瘤。", "A small angioma on the skin is usually harmless.", "皮肤上的小血管瘤通常无害。", 3, ["angio-", "-oma"]),
        ("arteriosclerosis", "/ɑːrˌtɪərioʊskləˈroʊsɪs/", "Thickening and hardening of the walls of arteries.", "动脉硬化：动脉壁增厚变硬。", "Arteriosclerosis reduces the elasticity of the arteries.", "动脉硬化使动脉弹性下降。", 3, ["arterio-", "-sclerosis"]),
        ("cardiac arrest", "/ˈkɑːrdiæk əˈrest/", "Sudden loss of heart function, breathing, and consciousness.", "心搏骤停：心脏功能、呼吸和意识突然丧失。", "Cardiac arrest requires immediate CPR and defibrillation.", "心搏骤停需立即进行心肺复苏和电除颤。", 3, ["cardi-"]),
    ],

    # ════════════════ System 2 · Respiratory ════════════════
    2: [
        ("bronchospasm", "/ˈbrɒŋkoʊspæzəm/", "Sudden tightening of the muscles around the bronchi, narrowing the airways.", "支气管痉挛：支气管周围肌肉突然收缩，使气道变窄。", "Bronchospasm during an asthma attack makes breathing difficult.", "哮喘发作时的支气管痉挛使呼吸困难。", 3, ["broncho-", "-spasm"]),
        ("bronchoscopy", "/brɒŋˈkɒskəpi/", "Visual examination of the airways using a flexible scope.", "支气管镜检查：用软镜观察气道。", "Bronchoscopy can be used to take a lung biopsy.", "支气管镜检查可用于取肺活检。", 3, ["broncho-", "-scopy"]),
        ("bronchodilator", "/ˌbrɒŋkoʊdaɪˈleɪtər/", "A drug that relaxes and widens the airways.", "支气管扩张剂：松弛并扩张气道的药物。", "Inhaled bronchodilators relieve wheezing quickly.", "吸入支气管扩张剂能迅速缓解喘鸣。", 2, ["broncho-"]),
        ("laryngitis", "/ˌlærɪnˈdʒaɪtɪs/", "Inflammation of the larynx (voice box), often causing hoarseness.", "喉炎：喉（发声器官）的炎症，常引起声音嘶哑。", "Laryngitis left the singer unable to perform.", "喉炎使这位歌手无法演出。", 2, ["laryngo-", "-itis"]),
        ("pharyngitis", "/ˌfærɪnˈdʒaɪtɪs/", "Inflammation of the pharynx (throat); a sore throat.", "咽炎：咽部的炎症，即咽喉痛。", "Viral pharyngitis usually resolves without antibiotics.", "病毒性咽炎通常无需抗生素即可痊愈。", 2, ["pharyngo-", "-itis"]),
        ("rhinitis", "/raɪˈnaɪtɪs/", "Inflammation of the lining of the nose.", "鼻炎：鼻黏膜的炎症。", "Allergic rhinitis causes sneezing and a runny nose.", "过敏性鼻炎引起打喷嚏和流涕。", 2, ["rhino-", "-itis"]),
        ("rhinorrhea", "/ˌraɪnoʊˈriːə/", "A persistent watery discharge from the nose; a runny nose.", "鼻溢液：持续的清水样鼻涕；流涕。", "Rhinorrhea is a common symptom of the common cold.", "流涕是普通感冒的常见症状。", 2, ["rhino-", "-rrhea"]),
        ("tracheostomy", "/ˌtreɪkiˈɒstəmi/", "A surgical opening created in the trachea to aid breathing.", "气管造口术：在气管上造口以辅助呼吸。", "A tracheostomy may be needed for long-term ventilation.", "长期机械通气可能需要气管造口。", 4, ["tracheo-", "-stomy"]),
        ("thoracotomy", "/ˌθɔːrəˈkɒtəmi/", "Surgical incision into the chest wall.", "开胸术：切开胸壁的手术。", "A thoracotomy gives surgeons access to the lungs.", "开胸术使外科医生能够进入肺部操作。", 4, ["thoraco-", "-tomy"]),
        ("thoracentesis", "/ˌθɔːrəsenˈtiːsɪs/", "Removal of fluid from the pleural space with a needle.", "胸腔穿刺术：用针抽出胸膜腔积液。", "Thoracentesis relieved the patient's breathlessness.", "胸腔穿刺术缓解了患者的呼吸困难。", 4, ["thoraco-", "-centesis"]),
        ("pleurisy", "/ˈplʊərɪsi/", "Inflammation of the pleura, causing sharp pain when breathing.", "胸膜炎：胸膜的炎症，呼吸时引起尖锐疼痛。", "Pleurisy causes pain that worsens with deep breaths.", "胸膜炎引起的疼痛在深呼吸时加重。", 3, ["pleuro-"]),
        ("pleural effusion", "/ˈplʊərəl ɪˈfjuːʒən/", "Buildup of excess fluid between the layers of the pleura.", "胸腔积液：胸膜各层之间积聚过多液体。", "A large pleural effusion can compress the lung.", "大量胸腔积液可压迫肺。", 3, ["pleuro-"]),
        ("hypoxia", "/haɪˈpɒksiə/", "A deficiency of oxygen reaching the body's tissues.", "缺氧：到达机体组织的氧气不足。", "Severe hypoxia can damage the brain within minutes.", "重度缺氧数分钟内即可损伤大脑。", 3, ["hypo-", "oxy-"]),
        ("hypoxemia", "/ˌhaɪpɒkˈsiːmiə/", "An abnormally low level of oxygen in the blood.", "低氧血症：血液中氧含量异常偏低。", "Hypoxemia is measured with a pulse oximeter.", "低氧血症可用脉搏血氧仪测量。", 3, ["hypo-", "oxy-", "-emia"]),
        ("tachypnea", "/ˌtækɪpˈniːə/", "Abnormally rapid breathing.", "呼吸急促：异常加快的呼吸。", "Tachypnea may be a sign of respiratory distress.", "呼吸急促可能是呼吸窘迫的征象。", 3, ["tachy-", "-pnea"]),
        ("bradypnea", "/ˌbreɪdɪpˈniːə/", "Abnormally slow breathing.", "呼吸过缓：异常减慢的呼吸。", "Certain drugs can cause bradypnea by depressing the brain.", "某些药物可抑制脑部而引起呼吸过缓。", 3, ["brady-", "-pnea"]),
        ("orthopnea", "/ɔːrˈθɒpniə/", "Shortness of breath that occurs when lying flat.", "端坐呼吸：平躺时出现的呼吸困难。", "Orthopnea forces some patients to sleep propped up on pillows.", "端坐呼吸迫使一些患者垫高枕头入睡。", 3, ["-pnea"]),
        ("atelectasis", "/ˌætɪˈlektəsɪs/", "Partial or complete collapse of a lung or part of it.", "肺不张：肺或其一部分的部分或完全塌陷。", "Atelectasis can develop after surgery if breaths are shallow.", "术后呼吸表浅时可发生肺不张。", 4, ["-ectasis"]),
        ("expectorant", "/ɪkˈspektərənt/", "A medicine that helps loosen and bring up mucus.", "祛痰药：帮助稀释并咳出黏液的药物。", "An expectorant can make a productive cough more effective.", "祛痰药能使咳痰更顺畅。", 2, []),
        ("sputum", "/ˈspjuːtəm/", "Mucus coughed up from the lower airways.", "痰：从下气道咳出的黏液。", "A sputum sample was sent to test for infection.", "送检痰标本以检测感染。", 2, []),
        ("wheeze", "/wiːz/", "A high-pitched whistling sound made while breathing.", "喘鸣：呼吸时发出的高调哨笛样声音。", "Wheezing is common in asthma and bronchitis.", "喘鸣常见于哮喘和支气管炎。", 1, []),
        ("hemothorax", "/ˌhiːmoʊˈθɔːræks/", "A collection of blood in the pleural cavity.", "血胸：胸膜腔内积血。", "Chest trauma can cause a hemothorax.", "胸部外伤可导致血胸。", 4, ["hemo-", "thoraco-"]),
        ("pulmonary", "/ˈpʌlməneri/", "Relating to the lungs.", "肺的：与肺相关的。", "The pulmonary arteries carry blood from the heart to the lungs.", "肺动脉将血液从心脏输送到肺。", 2, ["pulmo-"]),
        ("respiration", "/ˌrespɪˈreɪʃən/", "The process of breathing and exchanging gases.", "呼吸：呼吸并进行气体交换的过程。", "Respiration rate is counted as breaths per minute.", "呼吸频率以每分钟呼吸次数计。", 1, []),
        ("alveolitis", "/ˌælviəˈlaɪtɪs/", "Inflammation of the alveoli in the lungs.", "肺泡炎：肺泡的炎症。", "Inhaling certain dusts can trigger alveolitis.", "吸入某些粉尘可诱发肺泡炎。", 3, ["-itis"]),
        ("cyanosis (respiratory)", "/ˌsaɪəˈnoʊsɪs/", "Bluish discoloration of skin from low blood oxygen.", "发绀：因血氧偏低使皮肤呈青紫色。", "Central cyanosis is best seen on the lips and tongue.", "中心性发绀在唇和舌处最易观察到。", 3, ["cyano-", "-osis"]),
        ("dyspnea (exertional)", "/dɪspˈniːə/", "Difficult or labored breathing, especially on exertion.", "劳力性呼吸困难：呼吸费力，尤其在用力时。", "Exertional dyspnea may signal heart or lung disease.", "劳力性呼吸困难可能提示心肺疾病。", 2, ["dys-", "-pnea"]),
        ("apnea (sleep)", "/ˈæpniə/", "A temporary pause in breathing, as in sleep apnea.", "睡眠呼吸暂停：呼吸的暂时停止，如睡眠呼吸暂停。", "Sleep apnea causes repeated pauses in breathing at night.", "睡眠呼吸暂停使夜间呼吸反复中断。", 2, ["a-", "-pnea"]),
        ("nebulizer", "/ˈnebjəlaɪzər/", "A device that turns liquid medicine into a fine mist for inhaling.", "雾化器：将液体药物变成细雾以供吸入的装置。", "The child received salbutamol through a nebulizer.", "患儿通过雾化器吸入了沙丁胺醇。", 2, []),
        ("pneumonitis", "/ˌnjuːməˈnaɪtɪs/", "Inflammation of lung tissue not caused by infection.", "肺炎症（非感染性）：非感染引起的肺组织炎症。", "Radiation pneumonitis can follow chest radiotherapy.", "胸部放疗后可发生放射性肺炎。", 3, ["pneumon-", "-itis"]),
        ("tuberculosis", "/tjuːˌbɜːrkjəˈloʊsɪs/", "A contagious bacterial infection that mainly affects the lungs.", "结核病：主要侵犯肺部的传染性细菌感染。", "Tuberculosis is treated with a long course of antibiotics.", "结核病需用长疗程抗生素治疗。", 3, ["-osis"]),
        ("hyperventilation", "/ˌhaɪpərˌventɪˈleɪʃən/", "Breathing that is faster or deeper than the body needs.", "过度通气：呼吸频率或深度超过机体所需。", "Anxiety can trigger hyperventilation and tingling fingers.", "焦虑可诱发过度通气和手指麻刺感。", 2, ["hyper-"]),
    ],

    # ════════════════ System 3 · Nervous ════════════════
    3: [
        ("cerebrum", "/səˈriːbrəm/", "The largest part of the brain, responsible for thought and movement.", "大脑：脑最大的部分，负责思维和运动。", "The cerebrum is divided into two hemispheres.", "大脑分为两个半球。", 2, ["cerebro-"]),
        ("cerebellum", "/ˌserəˈbeləm/", "The brain region that coordinates movement and balance.", "小脑：协调运动和平衡的脑区。", "Damage to the cerebellum causes unsteady movements.", "小脑损伤会导致动作不稳。", 3, []),
        ("meninges", "/məˈnɪndʒiːz/", "The three protective membranes covering the brain and spinal cord.", "脑膜：覆盖脑和脊髓的三层保护膜。", "Infection of the meninges is called meningitis.", "脑膜的感染称为脑膜炎。", 3, ["meningo-"]),
        ("myelopathy", "/ˌmaɪəˈlɒpəθi/", "Any disease of the spinal cord.", "脊髓病：脊髓的任何疾病。", "Cervical myelopathy can cause weakness in the limbs.", "颈髓病可引起肢体无力。", 4, ["myelo-", "-pathy"]),
        ("encephalopathy", "/enˌsefəˈlɒpəθi/", "Any disease or dysfunction of the brain.", "脑病：脑的任何疾病或功能障碍。", "Liver failure can lead to hepatic encephalopathy.", "肝衰竭可导致肝性脑病。", 4, ["encephalo-", "-pathy"]),
        ("aphasia", "/əˈfeɪʒə/", "Loss of the ability to understand or produce speech.", "失语症：理解或表达言语能力的丧失。", "Aphasia is a common consequence of a left-sided stroke.", "失语症是左侧卒中的常见后果。", 3, ["a-", "-phasia"]),
        ("dysphasia", "/dɪsˈfeɪʒə/", "Impaired but not absent ability to use language.", "言语困难：语言能力受损但未完全丧失。", "Mild dysphasia may improve with speech therapy.", "轻度言语困难可通过言语治疗改善。", 3, ["dys-", "-phasia"]),
        ("hemiparesis", "/ˌhemipəˈriːsɪs/", "Weakness affecting one side of the body.", "偏身轻瘫：一侧身体的肌力减弱。", "The stroke left him with hemiparesis on the right.", "卒中使他右侧偏身轻瘫。", 3, ["-paresis"]),
        ("quadriplegia", "/ˌkwɒdrɪˈpliːdʒə/", "Paralysis of all four limbs.", "四肢瘫：四肢的瘫痪。", "A high spinal cord injury can cause quadriplegia.", "高位脊髓损伤可导致四肢瘫。", 4, ["-plegia"]),
        ("neuralgia (trigeminal)", "/njʊˈrældʒə/", "Sharp pain along the course of a nerve.", "神经痛：沿神经走行的尖锐疼痛。", "Trigeminal neuralgia causes brief, intense facial pain.", "三叉神经痛引起短暂而剧烈的面部疼痛。", 3, ["neuro-", "-algia"]),
        ("neuritis", "/njʊˈraɪtɪs/", "Inflammation of a nerve.", "神经炎：神经的炎症。", "Optic neuritis can cause sudden vision loss in one eye.", "视神经炎可引起单眼突然视力下降。", 3, ["neuro-", "-itis"]),
        ("neurogenesis", "/ˌnjʊəroʊˈdʒenəsɪs/", "The formation of new neurons in the brain.", "神经发生：脑内新神经元的生成。", "Neurogenesis continues in certain brain regions in adults.", "成人某些脑区仍持续存在神经发生。", 4, ["neuro-", "-genesis"]),
        ("anesthesia", "/ˌænəsˈθiːʒə/", "Loss of sensation, often induced for surgery.", "麻醉：感觉的丧失，常为手术而诱导。", "General anesthesia renders the patient unconscious.", "全身麻醉使患者失去意识。", 2, ["an-", "esthesi-"]),
        ("paresthesia", "/ˌpærəsˈθiːʒə/", "An abnormal tingling or 'pins and needles' sensation.", "感觉异常：异常的麻刺或「针扎」样感觉。", "Paresthesia in the hands may suggest nerve compression.", "手部感觉异常可能提示神经受压。", 3, ["esthesi-"]),
        ("convulsion", "/kənˈvʌlʃən/", "Sudden, violent, involuntary muscle contractions; a seizure.", "惊厥：突然、剧烈、不自主的肌肉收缩；抽搐。", "A high fever can trigger convulsions in young children.", "高热可诱发幼儿惊厥。", 2, []),
        ("seizure", "/ˈsiːʒər/", "A burst of abnormal electrical activity in the brain.", "癫痫发作：脑内异常电活动的爆发。", "Epilepsy is characterized by recurrent seizures.", "癫痫以反复发作为特征。", 2, []),
        ("Parkinson's disease", "/ˈpɑːrkɪnsənz dɪˈziːz/", "A progressive disorder causing tremor, stiffness, and slow movement.", "帕金森病：以震颤、僵硬和动作迟缓为特征的进行性疾病。", "Parkinson's disease results from loss of dopamine-producing neurons.", "帕金森病源于产生多巴胺的神经元丧失。", 3, []),
        ("multiple sclerosis", "/ˌmʌltɪpəl skləˈroʊsɪs/", "An autoimmune disease that damages the myelin of nerves.", "多发性硬化：损害神经髓鞘的自身免疫病。", "Multiple sclerosis can cause numbness, weakness, and vision problems.", "多发性硬化可引起麻木、无力和视力问题。", 4, ["-sclerosis"]),
        ("migraine", "/ˈmaɪɡreɪn/", "A recurrent, often one-sided, throbbing headache.", "偏头痛：反复发作、常为单侧的搏动性头痛。", "Migraines are sometimes preceded by visual aura.", "偏头痛有时先有视觉先兆。", 2, []),
        ("concussion", "/kənˈkʌʃən/", "A mild brain injury caused by a blow to the head.", "脑震荡：头部受击引起的轻度脑损伤。", "A concussion can cause headache, confusion, and dizziness.", "脑震荡可引起头痛、意识模糊和头晕。", 2, []),
        ("hydrocephalus", "/ˌhaɪdroʊˈsefələs/", "Buildup of fluid within the cavities of the brain.", "脑积水：脑腔内液体积聚。", "Hydrocephalus may enlarge the head in infants.", "脑积水在婴儿可使头部增大。", 4, ["encephalo-"]),
        ("neuropathy (peripheral)", "/njʊˈrɒpəθi/", "Damage to the peripheral nerves causing numbness or pain.", "周围神经病：周围神经损伤引起麻木或疼痛。", "Diabetic neuropathy often begins in the feet.", "糖尿病周围神经病常起于足部。", 3, ["neuro-", "-pathy"]),
        ("reflex", "/ˈriːfleks/", "An automatic, involuntary response to a stimulus.", "反射：对刺激的自动、不自主反应。", "The knee-jerk reflex tests the nervous system.", "膝跳反射用于检查神经系统。", 1, []),
        ("dendrite", "/ˈdendraɪt/", "A branching extension of a neuron that receives signals.", "树突：神经元接收信号的分支状突起。", "Dendrites carry impulses toward the cell body.", "树突将冲动传向胞体。", 3, []),
        ("neurotransmitter", "/ˌnjʊəroʊtrænsˈmɪtər/", "A chemical that carries signals across a synapse.", "神经递质：在突触间传递信号的化学物质。", "Dopamine and serotonin are well-known neurotransmitters.", "多巴胺和血清素是著名的神经递质。", 3, ["neuro-"]),
        ("comatose", "/ˈkoʊmətoʊs/", "In a coma; in a state of deep unconsciousness.", "昏迷的：处于深度无意识状态。", "The patient remained comatose after the injury.", "患者受伤后持续昏迷。", 3, []),
        ("vertigo", "/ˈvɜːrtɪɡoʊ/", "A sensation of spinning or that one's surroundings are spinning.", "眩晕：自身或周围环境旋转的感觉。", "Inner-ear problems are a common cause of vertigo.", "内耳问题是眩晕的常见原因。", 2, []),
        ("syncope", "/ˈsɪŋkəpi/", "Temporary loss of consciousness; fainting.", "晕厥：短暂的意识丧失；昏厥。", "Syncope often results from a brief drop in blood flow to the brain.", "晕厥常因脑供血短暂下降所致。", 3, []),
        ("polyneuropathy", "/ˌpɒlinjʊˈrɒpəθi/", "Simultaneous damage to many peripheral nerves.", "多发性神经病：多条周围神经同时受损。", "Polyneuropathy can cause symmetrical numbness in the limbs.", "多发性神经病可引起肢体对称性麻木。", 4, ["poly-", "neuro-", "-pathy"]),
        ("cerebrovascular", "/ˌserəbroʊˈvæskjələr/", "Relating to the blood vessels of the brain.", "脑血管的：与脑部血管相关的。", "A cerebrovascular accident is another name for a stroke.", "脑血管意外是卒中的另一名称。", 3, ["cerebro-"]),
        ("ataxia", "/əˈtæksiə/", "Loss of full control of body movements.", "共济失调：身体动作协调控制的丧失。", "Ataxia makes walking unsteady and clumsy.", "共济失调使步态不稳、笨拙。", 3, ["a-"]),
    ],

    # ════════════════ System 4 · Digestive ════════════════
    4: [
        ("esophagitis", "/ɪˌsɒfəˈdʒaɪtɪs/", "Inflammation of the esophagus.", "食管炎：食管的炎症。", "Acid reflux is a frequent cause of esophagitis.", "胃酸反流是食管炎的常见原因。", 3, ["esophag-", "-itis"]),
        ("gastroenteritis", "/ˌɡæstroʊˌentəˈraɪtɪs/", "Inflammation of the stomach and intestines, often from infection.", "胃肠炎：胃和肠的炎症，常由感染引起。", "Gastroenteritis causes vomiting, diarrhea, and cramps.", "胃肠炎引起呕吐、腹泻和腹部绞痛。", 2, ["gastro-", "entero-", "-itis"]),
        ("colitis", "/kəˈlaɪtɪs/", "Inflammation of the colon (large intestine).", "结肠炎：结肠（大肠）的炎症。", "Ulcerative colitis causes bloody diarrhea.", "溃疡性结肠炎引起血性腹泻。", 3, ["colo-", "-itis"]),
        ("proctitis", "/prɒkˈtaɪtɪs/", "Inflammation of the rectum and anus.", "直肠炎：直肠和肛门的炎症。", "Proctitis can cause rectal pain and bleeding.", "直肠炎可引起直肠疼痛和出血。", 3, ["procto-", "-itis"]),
        ("hepatomegaly (alcoholic)", "/ˌhepətoʊˈmeɡəli/", "Enlargement of the liver.", "肝肿大：肝脏体积增大。", "Hepatomegaly may be felt below the right rib cage.", "肝肿大可在右肋缘下触及。", 3, ["hepato-", "-megaly"]),
        ("cholelithiasis", "/ˌkoʊlɪlɪˈθaɪəsɪs/", "The presence of gallstones in the gallbladder.", "胆石症：胆囊内存在胆结石。", "Cholelithiasis can block bile flow and cause pain.", "胆石症可阻塞胆汁流出并引起疼痛。", 4, ["chole-", "litho-"]),
        ("cholecystectomy", "/ˌkoʊlɪsɪsˈtektəmi/", "Surgical removal of the gallbladder.", "胆囊切除术：手术切除胆囊。", "Cholecystectomy is a common treatment for gallstones.", "胆囊切除术是胆结石的常见治疗。", 4, ["cholecyst-", "-ectomy"]),
        ("pancreatitis", "/ˌpæŋkriəˈtaɪtɪs/", "Inflammation of the pancreas.", "胰腺炎：胰腺的炎症。", "Acute pancreatitis causes severe upper abdominal pain.", "急性胰腺炎引起剧烈上腹痛。", 3, ["pancreat-", "-itis"]),
        ("gastrectomy", "/ɡæsˈtrektəmi/", "Surgical removal of part or all of the stomach.", "胃切除术：手术切除部分或全部胃。", "A gastrectomy may be needed to treat stomach cancer.", "胃切除术可用于治疗胃癌。", 4, ["gastro-", "-ectomy"]),
        ("colonoscopy (screening)", "/ˌkoʊləˈnɒskəpi/", "Visual examination of the colon using a flexible scope.", "结肠镜检查：用软镜观察结肠。", "Colonoscopy can detect and remove precancerous polyps.", "结肠镜检查可发现并切除癌前息肉。", 3, ["colono-", "-scopy"]),
        ("laparotomy", "/ˌlæpəˈrɒtəmi/", "Surgical incision into the abdominal wall.", "剖腹术：切开腹壁的手术。", "An exploratory laparotomy is done to find the cause of pain.", "探查性剖腹术用于查找疼痛原因。", 4, ["lapar-", "-tomy"]),
        ("laparoscopy", "/ˌlæpəˈrɒskəpi/", "Examination of the abdomen through a small scope.", "腹腔镜检查：通过小型内镜检查腹腔。", "Laparoscopy allows surgery through tiny incisions.", "腹腔镜可通过微小切口进行手术。", 3, ["lapar-", "-scopy"]),
        ("hematemesis", "/ˌhiːməˈteməsɪs/", "Vomiting of blood.", "呕血：呕吐出血液。", "Hematemesis may indicate bleeding in the upper digestive tract.", "呕血可能提示上消化道出血。", 4, ["hema-", "-emesis"]),
        ("dyspepsia", "/dɪsˈpepsiə/", "Indigestion; discomfort in the upper abdomen.", "消化不良：上腹部不适。", "Dyspepsia often improves with smaller, slower meals.", "少食慢食常可改善消化不良。", 2, ["dys-"]),
        ("ascites", "/əˈsaɪtiːz/", "Abnormal buildup of fluid in the abdominal cavity.", "腹水：腹腔内液体异常积聚。", "Cirrhosis is a common cause of ascites.", "肝硬化是腹水的常见原因。", 4, []),
        ("jaundice", "/ˈdʒɔːndɪs/", "Yellowing of the skin and eyes from excess bilirubin.", "黄疸：因胆红素过多使皮肤和眼睛发黄。", "Jaundice is often a sign of liver or bile-duct disease.", "黄疸常是肝脏或胆道疾病的征象。", 2, []),
        ("constipation", "/ˌkɒnstɪˈpeɪʃən/", "Infrequent or difficult bowel movements.", "便秘：排便次数减少或排便困难。", "A high-fiber diet helps relieve constipation.", "高纤维饮食有助于缓解便秘。", 1, []),
        ("diarrhea", "/ˌdaɪəˈriːə/", "Frequent loose or watery bowel movements.", "腹泻：频繁的稀便或水样便。", "Diarrhea can quickly lead to dehydration in children.", "腹泻在儿童可迅速导致脱水。", 1, ["-rrhea"]),
        ("hemorrhoid", "/ˈhemərɔɪd/", "A swollen vein in the rectum or anus.", "痔：直肠或肛门处肿胀的静脉。", "Hemorrhoids may cause itching and bright-red bleeding.", "痔可引起瘙痒和鲜红色出血。", 2, ["hema-"]),
        ("appendectomy", "/ˌæpənˈdektəmi/", "Surgical removal of the appendix.", "阑尾切除术：手术切除阑尾。", "An appendectomy is the standard treatment for appendicitis.", "阑尾切除术是阑尾炎的标准治疗。", 3, ["-ectomy"]),
        ("malabsorption", "/ˌmæləbˈzɔːrpʃən/", "Impaired absorption of nutrients from the intestine.", "吸收不良：肠道对营养物质吸收障碍。", "Celiac disease causes malabsorption of nutrients.", "乳糜泻可引起营养吸收不良。", 3, []),
        ("reflux", "/ˈriːflʌks/", "The backward flow of stomach contents into the esophagus.", "反流：胃内容物倒流入食管。", "Acid reflux causes a burning sensation called heartburn.", "胃酸反流引起称为烧心的灼热感。", 2, []),
        ("hepatic", "/hɪˈpætɪk/", "Relating to the liver.", "肝的：与肝脏相关的。", "The hepatic portal vein drains blood from the intestine.", "肝门静脉引流来自肠道的血液。", 2, ["hepato-"]),
        ("enteritis (regional)", "/ˌentəˈraɪtɪs/", "Inflammation of the small intestine.", "肠炎：小肠的炎症。", "Crohn's disease can cause regional enteritis.", "克罗恩病可引起局限性肠炎。", 3, ["entero-", "-itis"]),
        ("stomatitis", "/ˌstoʊməˈtaɪtɪs/", "Inflammation of the mouth and lips.", "口炎：口腔和唇的炎症。", "Chemotherapy can cause painful stomatitis.", "化疗可引起疼痛的口炎。", 3, ["-itis"]),
        ("glossitis", "/ɡlɒˈsaɪtɪs/", "Inflammation of the tongue.", "舌炎：舌的炎症。", "Vitamin deficiencies can lead to glossitis.", "维生素缺乏可导致舌炎。", 3, ["glosso-", "-itis"]),
        ("ileus", "/ˈɪliəs/", "A lack of normal intestinal movement, blocking passage of contents.", "肠梗阻（麻痹性）：肠道正常蠕动缺失，致内容物通过受阻。", "Paralytic ileus can occur after abdominal surgery.", "麻痹性肠梗阻可发生于腹部手术后。", 4, []),
        ("peritonitis", "/ˌperɪtəˈnaɪtɪs/", "Inflammation of the peritoneum lining the abdomen.", "腹膜炎：覆盖腹腔的腹膜的炎症。", "A ruptured appendix can cause peritonitis.", "阑尾穿孔可引起腹膜炎。", 4, ["-itis"]),
        ("polyp", "/ˈpɒlɪp/", "A small growth projecting from a mucous membrane.", "息肉：自黏膜突出的小赘生物。", "Colon polyps can be removed during colonoscopy.", "结肠息肉可在结肠镜检查时切除。", 2, []),
        ("dysphagia (esophageal)", "/dɪsˈfeɪdʒə/", "Difficulty swallowing.", "吞咽困难：吞咽时困难。", "Dysphagia may result from a narrowed esophagus.", "吞咽困难可因食管狭窄所致。", 3, ["dys-", "-phagia"]),
        ("gastroscopy", "/ɡæsˈtrɒskəpi/", "Visual examination of the stomach using a scope.", "胃镜检查：用内镜观察胃。", "Gastroscopy can identify ulcers and tumors.", "胃镜检查可发现溃疡和肿瘤。", 3, ["gastro-", "-scopy"]),
    ],

    # ════════════════ System 5 · Musculoskeletal ════════════════
    5: [
        ("fracture", "/ˈfræktʃər/", "A break in a bone.", "骨折：骨的断裂。", "A fracture is confirmed and classified with an X-ray.", "骨折通过 X 线确诊并分型。", 1, []),
        ("osteomyelitis", "/ˌɒstioʊˌmaɪəˈlaɪtɪs/", "Infection of bone, usually by bacteria.", "骨髓炎：骨的感染，通常由细菌引起。", "Osteomyelitis may require prolonged antibiotics and surgery.", "骨髓炎可能需要长期抗生素和手术治疗。", 4, ["osteo-", "myelo-", "-itis"]),
        ("osteomalacia", "/ˌɒstioʊməˈleɪʃə/", "Softening of bones, often from vitamin D deficiency.", "骨软化症：骨骼软化，常因维生素 D 缺乏所致。", "Osteomalacia causes bone pain and muscle weakness.", "骨软化症引起骨痛和肌无力。", 4, ["osteo-", "-malacia"]),
        ("chondritis", "/kɒnˈdraɪtɪs/", "Inflammation of cartilage.", "软骨炎：软骨的炎症。", "Costochondritis is inflammation of rib cartilage.", "肋软骨炎是肋骨软骨的炎症。", 3, ["chondro-", "-itis"]),
        ("chondromalacia", "/ˌkɒndroʊməˈleɪʃə/", "Softening and breakdown of cartilage, often in the knee.", "软骨软化：软骨的软化与破坏，常见于膝。", "Chondromalacia of the kneecap causes pain when climbing stairs.", "髌骨软骨软化在上楼梯时引起疼痛。", 4, ["chondro-", "-malacia"]),
        ("arthralgia", "/ɑːrˈθrældʒə/", "Pain in a joint.", "关节痛：关节的疼痛。", "Arthralgia can accompany many viral infections.", "关节痛可伴随多种病毒感染。", 2, ["arthro-", "-algia"]),
        ("arthroplasty", "/ˈɑːrθroʊplæsti/", "Surgical reconstruction or replacement of a joint.", "关节成形术：关节的手术重建或置换。", "Hip arthroplasty can relieve severe arthritis pain.", "髋关节置换术可缓解严重的关节炎疼痛。", 4, ["arthro-", "-plasty"]),
        ("arthrodesis", "/ɑːrˈθrɒdɪsɪs/", "Surgical fusion of a joint to relieve pain.", "关节融合术：手术融合关节以缓解疼痛。", "Ankle arthrodesis stiffens the joint to reduce pain.", "踝关节融合术使关节固定以减轻疼痛。", 4, ["arthro-", "-desis"]),
        ("myalgia", "/maɪˈældʒə/", "Muscle pain.", "肌痛：肌肉的疼痛。", "Myalgia is a common symptom of influenza.", "肌痛是流感的常见症状。", 2, ["myo-", "-algia"]),
        ("myositis", "/ˌmaɪəˈsaɪtɪs/", "Inflammation of muscle tissue.", "肌炎：肌肉组织的炎症。", "Myositis causes muscle weakness and tenderness.", "肌炎引起肌无力和压痛。", 3, ["myo-", "-itis"]),
        ("tenosynovitis", "/ˌtenoʊˌsaɪnəˈvaɪtɪs/", "Inflammation of a tendon and its surrounding sheath.", "腱鞘炎：肌腱及其周围鞘膜的炎症。", "Repetitive movements can cause tenosynovitis of the wrist.", "重复动作可引起腕部腱鞘炎。", 3, ["teno-", "-itis"]),
        ("tenotomy", "/teˈnɒtəmi/", "Surgical cutting of a tendon.", "肌腱切断术：手术切断肌腱。", "Tenotomy can release a tight, contracted tendon.", "肌腱切断术可松解紧张挛缩的肌腱。", 4, ["teno-", "-tomy"]),
        ("spondylitis", "/ˌspɒndɪˈlaɪtɪs/", "Inflammation of the vertebrae of the spine.", "脊椎炎：脊柱椎骨的炎症。", "Ankylosing spondylitis can fuse the spine over time.", "强直性脊柱炎日久可使脊柱融合。", 4, ["spondylo-", "-itis"]),
        ("spondylosis", "/ˌspɒndɪˈloʊsɪs/", "Age-related degeneration of the spine.", "脊椎病：与年龄相关的脊柱退行性变。", "Cervical spondylosis can pinch nerves in the neck.", "颈椎病可压迫颈部神经。", 3, ["spondylo-", "-osis"]),
        ("osteotomy", "/ˌɒstiˈɒtəmi/", "Surgical cutting of bone to realign it.", "截骨术：切开骨以重新对位的手术。", "An osteotomy can correct a deformed leg bone.", "截骨术可矫正畸形的腿骨。", 4, ["osteo-", "-tomy"]),
        ("myopathy (inflammatory)", "/maɪˈɒpəθi/", "Any disease of muscle tissue.", "肌病：肌肉组织的任何疾病。", "Some myopathies are inherited and run in families.", "某些肌病为遗传性，呈家族聚集。", 3, ["myo-", "-pathy"]),
        ("luxation", "/lʌkˈseɪʃən/", "Complete dislocation of a joint.", "脱位：关节的完全脱位。", "Shoulder luxation often follows a fall on an outstretched arm.", "肩关节脱位常因手臂伸直跌倒所致。", 3, []),
        ("subluxation", "/ˌsʌblʌkˈseɪʃən/", "A partial dislocation of a joint.", "半脱位：关节的部分脱位。", "A subluxation leaves the joint partly out of place.", "半脱位使关节部分错位。", 3, ["sub-"]),
        ("sprain", "/spreɪn/", "An injury to a ligament from overstretching or tearing.", "扭伤：韧带因过度拉伸或撕裂而受伤。", "An ankle sprain is treated with rest, ice, and elevation.", "踝关节扭伤以休息、冰敷和抬高处理。", 1, []),
        ("strain", "/streɪn/", "An injury to a muscle or tendon from overuse or overstretching.", "拉伤：肌肉或肌腱因过用或过度拉伸而受伤。", "A hamstring strain is common in sprinters.", "腘绳肌拉伤在短跑运动员中常见。", 1, []),
        ("kyphosis", "/kaɪˈfoʊsɪs/", "Excessive outward curvature of the upper spine; hunchback.", "脊柱后凸：上段脊柱向后过度弯曲；驼背。", "Osteoporosis can lead to kyphosis in older adults.", "骨质疏松可导致老年人脊柱后凸。", 3, ["-osis"]),
        ("lordosis", "/lɔːrˈdoʊsɪs/", "Excessive inward curvature of the lower spine.", "脊柱前凸：下段脊柱向前过度弯曲。", "Pregnancy can temporarily increase lordosis.", "妊娠可暂时加重脊柱前凸。", 3, ["-osis"]),
        ("osteopenia", "/ˌɒstioʊˈpiːniə/", "Lower-than-normal bone density, milder than osteoporosis.", "骨量减少：骨密度低于正常，程度轻于骨质疏松。", "Osteopenia may progress to osteoporosis if untreated.", "骨量减少若不治疗可发展为骨质疏松。", 3, ["osteo-", "-penia"]),
        ("rhabdomyolysis", "/ˌræbdoʊmaɪˈɒlɪsɪs/", "Breakdown of muscle tissue that releases harmful contents into blood.", "横纹肌溶解：肌肉组织分解并将有害物质释入血液。", "Severe rhabdomyolysis can damage the kidneys.", "重度横纹肌溶解可损伤肾脏。", 4, ["myo-", "-lysis"]),
        ("fasciitis", "/ˌfæʃiˈaɪtɪs/", "Inflammation of the fascia, connective tissue beneath the skin.", "筋膜炎：皮下结缔组织（筋膜）的炎症。", "Plantar fasciitis causes heel pain with the first steps of the day.", "足底筋膜炎在清晨起步时引起足跟痛。", 3, ["-itis"]),
        ("ligament", "/ˈlɪɡəmənt/", "A band of tissue connecting bones at a joint.", "韧带：在关节处连接骨与骨的组织带。", "The anterior cruciate ligament stabilizes the knee.", "前交叉韧带稳定膝关节。", 1, []),
        ("tendon", "/ˈtendən/", "A cord of tissue that attaches muscle to bone.", "肌腱：将肌肉连于骨的索状组织。", "The Achilles tendon connects the calf muscle to the heel.", "跟腱将小腿肌连于足跟。", 1, ["tendin-"]),
        ("orthopedics", "/ˌɔːrθəˈpiːdɪks/", "The branch of medicine dealing with the musculoskeletal system.", "骨科：处理肌肉骨骼系统的医学分支。", "She saw an orthopedics specialist about her knee.", "她因膝盖问题就诊于骨科专家。", 2, []),
        ("dystrophy", "/ˈdɪstrəfi/", "Progressive weakening and degeneration, as of muscle.", "营养不良/萎缩症：进行性的衰弱和退变，如肌肉。", "Muscular dystrophy progressively weakens the muscles.", "肌营养不良症使肌肉进行性无力。", 3, ["dys-", "-trophy"]),
        ("crepitus", "/ˈkrepɪtəs/", "A grating sound or sensation from bone or joint movement.", "骨擦音/捻发感：骨或关节活动时的摩擦声或感觉。", "Crepitus is often felt in osteoarthritic joints.", "骨关节炎的关节常可触及捻发感。", 3, []),
    ],

    # ════════════════ System 6 · Endocrine ════════════════
    6: [
        ("hormone", "/ˈhɔːrmoʊn/", "A chemical messenger released by a gland into the blood.", "激素：腺体释放入血的化学信使。", "Insulin is a hormone made by the pancreas.", "胰岛素是胰腺分泌的一种激素。", 1, []),
        ("endocrine", "/ˈendoʊkrɪn/", "Relating to glands that secrete hormones into the blood.", "内分泌的：与将激素分泌入血的腺体相关。", "The endocrine system controls metabolism and growth.", "内分泌系统调控代谢和生长。", 2, ["endo-"]),
        ("hyperglycemia (fasting)", "/ˌhaɪpərɡlaɪˈsiːmiə/", "Abnormally high blood glucose.", "高血糖：血糖异常升高。", "Persistent hyperglycemia damages blood vessels.", "持续高血糖会损伤血管。", 3, ["hyper-", "glyco-", "-emia"]),
        ("glycosuria", "/ˌɡlaɪkoʊˈsjʊəriə/", "The presence of glucose in the urine.", "糖尿：尿中出现葡萄糖。", "Glycosuria occurs when blood sugar exceeds the kidney's threshold.", "当血糖超过肾阈值时出现糖尿。", 3, ["glyco-", "-uria"]),
        ("polydipsia", "/ˌpɒliˈdɪpsiə/", "Excessive thirst.", "多饮：异常口渴、饮水过多。", "Polydipsia and frequent urination are early signs of diabetes.", "多饮和尿频是糖尿病的早期征象。", 3, ["poly-", "-dipsia"]),
        ("polyuria", "/ˌpɒliˈjʊəriə/", "Production of abnormally large amounts of urine.", "多尿：尿量异常增多。", "Polyuria can lead to dehydration if fluids are not replaced.", "多尿若不补液可导致脱水。", 3, ["poly-", "-uria"]),
        ("goiter", "/ˈɡɔɪtər/", "An abnormal enlargement of the thyroid gland.", "甲状腺肿：甲状腺的异常增大。", "Iodine deficiency is a classic cause of goiter.", "碘缺乏是甲状腺肿的典型病因。", 3, []),
        ("thyromegaly", "/ˌθaɪroʊˈmeɡəli/", "Enlargement of the thyroid gland.", "甲状腺肿大：甲状腺的增大。", "Thyromegaly may be visible as a swelling in the neck.", "甲状腺肿大可表现为颈部肿胀。", 3, ["thyro-", "-megaly"]),
        ("thyroidectomy", "/ˌθaɪrɔɪˈdektəmi/", "Surgical removal of the thyroid gland.", "甲状腺切除术：手术切除甲状腺。", "Thyroidectomy may be used to treat thyroid cancer.", "甲状腺切除术可用于治疗甲状腺癌。", 4, ["thyro-", "-ectomy"]),
        ("adrenaline", "/əˈdrenəlɪn/", "A hormone that prepares the body for 'fight or flight'.", "肾上腺素：使机体准备「战或逃」反应的激素。", "Adrenaline raises heart rate and opens the airways.", "肾上腺素提高心率并扩张气道。", 2, ["adreno-"]),
        ("adrenalectomy", "/əˌdriːnəˈlektəmi/", "Surgical removal of an adrenal gland.", "肾上腺切除术：手术切除肾上腺。", "Adrenalectomy may treat a hormone-secreting tumor.", "肾上腺切除术可治疗分泌激素的肿瘤。", 4, ["adreno-", "-ectomy"]),
        ("adenopathy", "/ˌædɪˈnɒpəθi/", "Disease or enlargement of glands, especially lymph nodes.", "腺病：腺体（尤其淋巴结）的疾病或肿大。", "Cervical adenopathy means swollen glands in the neck.", "颈部腺病指颈部淋巴结肿大。", 3, ["aden-", "-pathy"]),
        ("hypersecretion", "/ˌhaɪpərsɪˈkriːʃən/", "Excessive secretion of a substance such as a hormone.", "分泌过多：某物质（如激素）的过度分泌。", "Hypersecretion of growth hormone can cause acromegaly.", "生长激素分泌过多可引起肢端肥大症。", 3, ["hyper-"]),
        ("hyposecretion", "/ˌhaɪpoʊsɪˈkriːʃən/", "Deficient secretion of a substance such as a hormone.", "分泌不足：某物质（如激素）的分泌减少。", "Hyposecretion of insulin contributes to diabetes.", "胰岛素分泌不足是糖尿病的成因之一。", 3, ["hypo-"]),
        ("acromegaly", "/ˌækroʊˈmeɡəli/", "Enlargement of the hands, feet, and face from excess growth hormone.", "肢端肥大症：生长激素过多使手、足和面部增大。", "Acromegaly develops slowly in adults over many years.", "肢端肥大症在成人中历经多年缓慢进展。", 4, ["-megaly"]),
        ("Cushing's syndrome", "/ˈkʊʃɪŋz ˈsɪndroʊm/", "A disorder caused by prolonged exposure to high cortisol.", "库欣综合征：长期高皮质醇暴露所致的疾病。", "Cushing's syndrome causes weight gain and a rounded face.", "库欣综合征引起体重增加和满月脸。", 4, []),
        ("Addison's disease", "/ˈædɪsənz dɪˈziːz/", "A disorder in which the adrenal glands produce too little hormone.", "艾迪生病：肾上腺激素生成过少的疾病。", "Addison's disease causes fatigue, low blood pressure, and skin darkening.", "艾迪生病引起乏力、低血压和皮肤变黑。", 4, []),
        ("hypopituitarism", "/ˌhaɪpoʊpɪˈtjuːɪtərɪzəm/", "Reduced hormone production by the pituitary gland.", "垂体功能减退：垂体激素生成减少。", "Hypopituitarism may affect growth, metabolism, and reproduction.", "垂体功能减退可影响生长、代谢和生殖。", 4, ["hypo-"]),
        ("metabolism", "/məˈtæbəlɪzəm/", "All the chemical processes that maintain life in the body.", "代谢：维持机体生命的全部化学过程。", "Thyroid hormones set the body's basal metabolism.", "甲状腺激素设定机体的基础代谢。", 2, []),
        ("electrolyte", "/ɪˈlektrəlaɪt/", "A mineral in body fluids that carries an electric charge.", "电解质：体液中带电荷的矿物质。", "Sodium and potassium are important electrolytes.", "钠和钾是重要的电解质。", 2, []),
        ("hyperkalemia", "/ˌhaɪpərkəˈliːmiə/", "Abnormally high level of potassium in the blood.", "高钾血症：血钾水平异常升高。", "Severe hyperkalemia can cause dangerous heart rhythms.", "重度高钾血症可引起危险的心律失常。", 4, ["hyper-", "-emia"]),
        ("hypokalemia", "/ˌhaɪpoʊkəˈliːmiə/", "Abnormally low level of potassium in the blood.", "低钾血症：血钾水平异常偏低。", "Hypokalemia can cause muscle weakness and cramps.", "低钾血症可引起肌无力和痉挛。", 4, ["hypo-", "-emia"]),
        ("hypercalcemia", "/ˌhaɪpərkælˈsiːmiə/", "Abnormally high level of calcium in the blood.", "高钙血症：血钙水平异常升高。", "Hypercalcemia may cause kidney stones and confusion.", "高钙血症可引起肾结石和意识模糊。", 4, ["hyper-", "-emia"]),
        ("euthyroid", "/juːˈθaɪrɔɪd/", "Having a normally functioning thyroid gland.", "甲状腺功能正常：甲状腺功能处于正常状态。", "After treatment, the patient became euthyroid.", "治疗后患者甲状腺功能恢复正常。", 3, ["thyro-"]),
        ("ketoacidosis", "/ˌkiːtoʊˌæsɪˈdoʊsɪs/", "A dangerous buildup of acids when the body breaks down fat for fuel.", "酮症酸中毒：机体分解脂肪供能时酸性物质危险性积聚。", "Diabetic ketoacidosis is a medical emergency.", "糖尿病酮症酸中毒是急症。", 4, ["-osis"]),
        ("glucagon", "/ˈɡluːkəɡɒn/", "A pancreatic hormone that raises blood glucose.", "胰高血糖素：升高血糖的胰腺激素。", "Glucagon is released when blood sugar falls too low.", "血糖过低时释放胰高血糖素。", 3, ["gluco-"]),
        ("insulin resistance", "/ˈɪnsəlɪn rɪˈzɪstəns/", "Reduced response of cells to insulin.", "胰岛素抵抗：细胞对胰岛素的反应减弱。", "Insulin resistance is central to type 2 diabetes.", "胰岛素抵抗是 2 型糖尿病的核心机制。", 3, []),
        ("pituitary", "/pɪˈtjuːɪtəri/", "The 'master gland' that controls other endocrine glands.", "垂体：调控其他内分泌腺的「主腺」。", "The pituitary releases hormones that direct the thyroid and adrenals.", "垂体释放激素以指挥甲状腺和肾上腺。", 2, []),
        ("hypothalamus", "/ˌhaɪpoʊˈθæləməs/", "A brain region linking the nervous and endocrine systems.", "下丘脑：连接神经系统与内分泌系统的脑区。", "The hypothalamus signals the pituitary to release hormones.", "下丘脑发出信号促使垂体释放激素。", 3, ["hypo-"]),
        ("hyperthyroid (state)", "/ˌhaɪpərˈθaɪrɔɪd/", "Relating to an overactive thyroid gland.", "甲状腺功能亢进的：与甲状腺功能过度活跃相关。", "A hyperthyroid patient may lose weight despite eating well.", "甲亢患者尽管进食良好仍可体重下降。", 3, ["hyper-", "thyro-"]),
    ],

    # ════════════════ System 7 · Urinary ════════════════
    7: [
        ("nephron", "/ˈnefrɒn/", "The microscopic filtering unit of the kidney.", "肾单位：肾脏的微观过滤单元。", "Each kidney contains about a million nephrons.", "每个肾脏约含一百万个肾单位。", 3, ["nephro-"]),
        ("nephrolithiasis", "/ˌnefroʊlɪˈθaɪəsɪs/", "The presence of stones in the kidney.", "肾结石症：肾脏内存在结石。", "Nephrolithiasis can cause severe flank pain.", "肾结石症可引起剧烈的腰侧疼痛。", 4, ["nephro-", "litho-"]),
        ("pyelonephritis", "/ˌpaɪɪloʊnɪˈfraɪtɪs/", "Infection and inflammation of the kidney, often from a UTI.", "肾盂肾炎：肾脏的感染和炎症，常源于尿路感染。", "Pyelonephritis causes fever, chills, and back pain.", "肾盂肾炎引起发热、寒战和腰背痛。", 4, ["pyelo-", "nephro-", "-itis"]),
        ("pyuria", "/paɪˈjʊəriə/", "The presence of pus (white blood cells) in the urine.", "脓尿：尿中出现脓液（白细胞）。", "Pyuria suggests a urinary tract infection.", "脓尿提示尿路感染。", 3, ["-uria"]),
        ("dysuria", "/dɪsˈjʊəriə/", "Painful or difficult urination.", "排尿困难/尿痛：排尿疼痛或困难。", "Dysuria is a common symptom of cystitis.", "尿痛是膀胱炎的常见症状。", 2, ["dys-", "-uria"]),
        ("oliguria", "/ˌɒlɪˈɡjʊəriə/", "Production of an abnormally small amount of urine.", "少尿：尿量异常减少。", "Oliguria can be an early sign of kidney failure.", "少尿可能是肾衰竭的早期征象。", 3, ["olig-", "-uria"]),
        ("anuria", "/əˈnjʊəriə/", "Failure of the kidneys to produce urine.", "无尿：肾脏不能产生尿液。", "Anuria indicates a severe loss of kidney function.", "无尿提示肾功能严重丧失。", 4, ["an-", "-uria"]),
        ("nocturia", "/nɒkˈtjʊəriə/", "The need to wake and urinate during the night.", "夜尿症：夜间需醒来排尿。", "Nocturia can disrupt sleep in older adults.", "夜尿症可扰乱老年人的睡眠。", 2, ["-uria"]),
        ("cystoscopy (diagnostic)", "/sɪsˈtɒskəpi/", "Visual examination of the bladder using a scope.", "膀胱镜检查：用内镜观察膀胱。", "Cystoscopy can find tumors and stones in the bladder.", "膀胱镜检查可发现膀胱内的肿瘤和结石。", 3, ["cysto-", "-scopy"]),
        ("cystectomy", "/sɪsˈtektəmi/", "Surgical removal of all or part of the bladder.", "膀胱切除术：手术切除全部或部分膀胱。", "Cystectomy may be required for invasive bladder cancer.", "浸润性膀胱癌可能需要膀胱切除术。", 4, ["cysto-", "-ectomy"]),
        ("ureteritis", "/jʊˌriːtəˈraɪtɪs/", "Inflammation of a ureter.", "输尿管炎：输尿管的炎症。", "Ureteritis may accompany a urinary tract infection.", "输尿管炎可伴随尿路感染。", 3, ["uretero-", "-itis"]),
        ("urethritis", "/ˌjʊərɪˈθraɪtɪs/", "Inflammation of the urethra.", "尿道炎：尿道的炎症。", "Urethritis causes burning during urination.", "尿道炎引起排尿灼痛。", 2, ["urethro-", "-itis"]),
        ("nephrotic syndrome", "/nɪˈfrɒtɪk ˈsɪndroʊm/", "A kidney disorder causing heavy protein loss in urine and swelling.", "肾病综合征：以尿中大量蛋白丢失和水肿为特征的肾病。", "Nephrotic syndrome causes foamy urine and body swelling.", "肾病综合征引起泡沫尿和全身水肿。", 4, ["nephro-"]),
        ("renal failure", "/ˈriːnəl ˈfeɪljər/", "Loss of the kidneys' ability to filter waste from the blood.", "肾衰竭：肾脏过滤血液废物能力的丧失。", "Chronic renal failure may eventually require dialysis.", "慢性肾衰竭最终可能需要透析。", 3, ["reno-"]),
        ("hemodialysis", "/ˌhiːmoʊdaɪˈælɪsɪs/", "Filtering the blood with a machine when the kidneys fail.", "血液透析：肾衰竭时用机器过滤血液。", "He undergoes hemodialysis three times a week.", "他每周接受三次血液透析。", 3, ["hemo-", "-lysis"]),
        ("incontinence", "/ɪnˈkɒntɪnəns/", "Inability to control urination.", "尿失禁：不能控制排尿。", "Stress incontinence can occur when coughing or laughing.", "压力性尿失禁可在咳嗽或大笑时发生。", 2, []),
        ("urology", "/jʊˈrɒlədʒi/", "The branch of medicine dealing with the urinary tract.", "泌尿外科学：处理泌尿系统的医学分支。", "He was referred to urology for kidney stones.", "他因肾结石被转诊至泌尿外科。", 2, ["uro-", "-logy"]),
        ("urolithiasis (recurrent)", "/ˌjʊəroʊlɪˈθaɪəsɪs/", "The formation of stones anywhere in the urinary tract.", "尿石症：泌尿系统任何部位结石的形成。", "Drinking more water helps prevent urolithiasis.", "多饮水有助于预防尿石症。", 3, ["uro-", "litho-"]),
        ("nephropathy", "/nɪˈfrɒpəθi/", "Any disease of the kidneys.", "肾病：肾脏的任何疾病。", "Diabetic nephropathy is a leading cause of kidney failure.", "糖尿病肾病是肾衰竭的主要原因之一。", 3, ["nephro-", "-pathy"]),
        ("nephrostomy", "/nɪˈfrɒstəmi/", "A surgical opening into the kidney to drain urine.", "肾造瘘术：在肾脏造口以引流尿液。", "A nephrostomy tube can drain an obstructed kidney.", "肾造瘘管可引流梗阻的肾脏。", 4, ["nephro-", "-stomy"]),
        ("lithotripsy", "/ˈlɪθoʊtrɪpsi/", "Breaking up stones using shock waves.", "碎石术：用冲击波击碎结石。", "Lithotripsy can shatter kidney stones without surgery.", "碎石术可在无需手术的情况下击碎肾结石。", 4, ["litho-"]),
        ("hematuria (gross)", "/ˌhiːməˈtjʊəriə/", "The presence of blood in the urine.", "血尿：尿中出现血液。", "Painless hematuria should always be investigated.", "无痛性血尿应始终进一步检查。", 3, ["hema-", "-uria"]),
        ("glomerulus", "/ɡlɒˈmerjələs/", "A tuft of capillaries in the nephron where blood is filtered.", "肾小球：肾单位中过滤血液的毛细血管丛。", "Damage to the glomerulus lets protein leak into urine.", "肾小球损伤会使蛋白漏入尿中。", 3, ["glomerulo-"]),
        ("renal", "/ˈriːnəl/", "Relating to the kidneys.", "肾的：与肾脏相关的。", "Renal arteries deliver blood to the kidneys.", "肾动脉将血液输送到肾脏。", 2, ["reno-"]),
        ("micturition", "/ˌmɪktjʊˈrɪʃən/", "The act of urinating.", "排尿：排出尿液的动作。", "Micturition is controlled by muscles of the bladder.", "排尿由膀胱肌肉控制。", 3, []),
        ("cystocele", "/ˈsɪstoʊsiːl/", "A bulging of the bladder into the vaginal wall.", "膀胱膨出：膀胱向阴道壁膨出。", "A cystocele can cause a feeling of pelvic pressure.", "膀胱膨出可引起盆腔坠胀感。", 4, ["cysto-", "-cele"]),
        ("uremia (chronic)", "/jʊˈriːmiə/", "A toxic buildup of waste in the blood from kidney failure.", "尿毒症：肾衰竭使废物在血中蓄积的中毒状态。", "Uremia causes nausea, fatigue, and confusion.", "尿毒症引起恶心、乏力和意识模糊。", 4, ["uro-", "-emia"]),
        ("polycystic kidney", "/ˌpɒliˈsɪstɪk ˈkɪdni/", "An inherited disease in which cysts fill the kidneys.", "多囊肾：囊肿充满肾脏的遗传性疾病。", "Polycystic kidney disease can gradually impair kidney function.", "多囊肾病可逐渐损害肾功能。", 4, ["poly-", "cysto-"]),
        ("diuretic", "/ˌdaɪjʊˈretɪk/", "A drug that increases the production of urine.", "利尿剂：增加尿液生成的药物。", "Diuretics help reduce swelling in heart failure.", "利尿剂有助于减轻心力衰竭的水肿。", 2, []),
        ("urinary catheter", "/ˈjʊərɪneri ˈkæθɪtər/", "A tube inserted to drain urine from the bladder.", "导尿管：插入以从膀胱引流尿液的管子。", "A urinary catheter may be placed after surgery.", "术后可能留置导尿管。", 2, []),
    ],

    # ════════════════ System 8 · Integumentary ════════════════
    8: [
        ("furuncle", "/ˈfjʊərʌŋkəl/", "A painful, pus-filled infection of a hair follicle; a boil.", "疖：毛囊的疼痛性化脓感染；俗称疖子。", "A furuncle usually drains and heals once it comes to a head.", "疖通常在成熟出头后引流并愈合。", 2, []),
        ("dermatomycosis", "/ˌdɜːrmətoʊmaɪˈkoʊsɪs/", "A fungal infection of the skin.", "皮肤真菌病：皮肤的真菌感染。", "Dermatomycosis often appears as itchy, scaly patches.", "皮肤真菌病常表现为瘙痒、脱屑的斑片。", 4, ["dermat-", "-osis"]),
        ("keratosis", "/ˌkerəˈtoʊsɪs/", "A thickened, horny growth of the skin.", "角化病：皮肤增厚的角质性赘生。", "Actinic keratosis is caused by long-term sun exposure.", "光化性角化病由长期日晒引起。", 3, ["kerato-", "-osis"]),
        ("melanocyte", "/məˈlænoʊsaɪt/", "A skin cell that produces the pigment melanin.", "黑素细胞：产生黑色素的皮肤细胞。", "Melanocytes give skin and hair their color.", "黑素细胞赋予皮肤和毛发颜色。", 3, ["melano-", "cyto-"]),
        ("onychomycosis", "/ˌɒnɪkoʊmaɪˈkoʊsɪs/", "A fungal infection of the nails.", "甲真菌病：指（趾）甲的真菌感染。", "Onychomycosis thickens and discolors the nails.", "甲真菌病使指甲增厚、变色。", 4, ["onycho-", "-osis"]),
        ("onycholysis", "/ˌɒnɪˈkɒlɪsɪs/", "Separation of a nail from its bed.", "甲剥离：甲与甲床的分离。", "Onycholysis can follow injury or a fungal infection.", "甲剥离可继发于外伤或真菌感染。", 4, ["onycho-", "-lysis"]),
        ("trichosis", "/trɪˈkoʊsɪs/", "Any abnormal condition or disease of the hair.", "毛发病：毛发的任何异常或疾病。", "Trichosis is a general term for hair disorders.", "毛发病是毛发疾病的统称。", 3, ["tricho-", "-osis"]),
        ("alopecia", "/ˌæləˈpiːʃə/", "Partial or complete loss of hair.", "脱发：毛发的部分或完全丧失。", "Alopecia areata causes patchy hair loss.", "斑秃引起片状脱发。", 3, []),
        ("xeroderma", "/ˌzɪəroʊˈdɜːrmə/", "Abnormally dry skin.", "皮肤干燥症：皮肤异常干燥。", "Xeroderma is common in cold, dry weather.", "皮肤干燥症在寒冷干燥的天气常见。", 3, ["xero-", "dermo-"]),
        ("erythroderma", "/ɪˌrɪθroʊˈdɜːrmə/", "Widespread redness of the skin over most of the body.", "红皮病：皮肤大面积广泛发红。", "Erythroderma can be a sign of a severe skin reaction.", "红皮病可能是严重皮肤反应的征象。", 4, ["erythro-", "dermo-"]),
        ("pruritus", "/prʊˈraɪtəs/", "Severe itching of the skin.", "瘙痒：皮肤的剧烈痒感。", "Pruritus can disturb sleep and lead to scratching.", "瘙痒可扰乱睡眠并导致搔抓。", 2, []),
        ("urticaria", "/ˌɜːrtɪˈkeəriə/", "Raised, itchy welts on the skin; hives.", "荨麻疹：皮肤上凸起、瘙痒的风团。", "Urticaria is often an allergic reaction.", "荨麻疹常为过敏反应。", 2, []),
        ("abscess", "/ˈæbses/", "A localized collection of pus within tissue.", "脓肿：组织内局限性脓液积聚。", "A skin abscess usually needs to be drained.", "皮肤脓肿通常需要切开引流。", 2, []),
        ("impetigo", "/ˌɪmpɪˈtaɪɡoʊ/", "A contagious bacterial skin infection with honey-colored crusts.", "脓疱病：以蜜黄色结痂为特征的传染性细菌性皮肤感染。", "Impetigo is common in young children.", "脓疱病在幼儿中常见。", 3, []),
        ("petechiae", "/pɪˈtiːkii/", "Tiny red or purple spots caused by minor bleeding under the skin.", "瘀点：皮下少量出血引起的微小红色或紫色斑点。", "Petechiae may appear when platelet counts are low.", "血小板减少时可出现瘀点。", 3, []),
        ("ecchymosis", "/ˌekɪˈmoʊsɪs/", "A bruise; discoloration from bleeding under the skin.", "瘀斑：皮下出血引起的变色；青肿。", "Ecchymosis spreads and changes color as it heals.", "瘀斑在愈合过程中扩散并变色。", 3, ["-osis"]),
        ("cyanotic", "/ˌsaɪəˈnɒtɪk/", "Showing a bluish skin color from lack of oxygen.", "发绀的：因缺氧而呈青紫色的。", "The newborn's lips looked cyanotic at birth.", "新生儿出生时口唇呈发绀。", 3, ["cyano-"]),
        ("subcutaneous", "/ˌsʌbkjuːˈteɪniəs/", "Located or introduced beneath the skin.", "皮下的：位于或注入皮肤之下。", "Insulin is given by subcutaneous injection.", "胰岛素通过皮下注射给药。", 2, ["sub-"]),
        ("epidermal", "/ˌepɪˈdɜːrməl/", "Relating to the epidermis, the outer layer of skin.", "表皮的：与皮肤外层（表皮）相关。", "Epidermal cells are constantly shed and replaced.", "表皮细胞不断脱落并被替换。", 2, ["dermo-"]),
        ("dermatologist", "/ˌdɜːrməˈtɒlədʒɪst/", "A doctor who specializes in skin diseases.", "皮肤科医生：专门诊治皮肤疾病的医生。", "A dermatologist examined the suspicious mole.", "皮肤科医生检查了那颗可疑的痣。", 2, ["dermat-", "-logy"]),
        ("dermatoplasty", "/ˈdɜːrmətoʊplæsti/", "Surgical repair or grafting of the skin.", "皮肤成形术：皮肤的手术修复或移植。", "Dermatoplasty may be needed after a severe burn.", "严重烧伤后可能需要皮肤成形术。", 4, ["dermat-", "-plasty"]),
        ("cellulitis (spreading)", "/ˌseljəˈlaɪtɪs/", "A bacterial infection of the deep layers of the skin.", "蜂窝织炎：皮肤深层的细菌感染。", "Cellulitis causes a warm, red, tender area of skin.", "蜂窝织炎引起皮肤温热、发红、压痛。", 3, ["-itis"]),
        ("ulcer (pressure)", "/ˈʌlsər/", "An open sore on the skin or a mucous membrane.", "溃疡：皮肤或黏膜上的开放性创面。", "A pressure ulcer can form over a bony area in bedridden patients.", "压疮可在卧床患者骨突部位形成。", 2, []),
        ("scabies", "/ˈskeɪbiːz/", "A contagious skin infestation by tiny mites causing intense itching.", "疥疮：由微小螨虫引起的传染性皮肤侵染，剧烈瘙痒。", "Scabies spreads through close skin contact.", "疥疮通过密切皮肤接触传播。", 3, []),
        ("verruca", "/vəˈruːkə/", "A wart, caused by a viral skin infection.", "疣：由病毒性皮肤感染引起。", "A verruca on the sole of the foot can be painful.", "足底的疣可引起疼痛。", 2, []),
        ("nevus", "/ˈniːvəs/", "A mole; a usually benign pigmented spot on the skin.", "痣：皮肤上通常良性的色素斑。", "A changing nevus should be checked for skin cancer.", "发生变化的痣应检查是否为皮肤癌。", 3, []),
        ("seborrhea", "/ˌsebəˈriːə/", "Excessive discharge of oil (sebum) from the skin.", "皮脂溢出：皮肤油脂（皮脂）的过度分泌。", "Seborrhea can lead to oily skin and dandruff.", "皮脂溢出可导致油性皮肤和头皮屑。", 3, ["-rrhea"]),
        ("keloid", "/ˈkiːlɔɪd/", "An overgrowth of scar tissue beyond the original wound.", "瘢痕疙瘩：超出原创面范围的瘢痕组织过度增生。", "Keloids can form after ear piercing or surgery.", "瘢痕疙瘩可在穿耳或手术后形成。", 3, []),
        ("melanoma (malignant)", "/ˌmeləˈnoʊmə/", "A dangerous skin cancer arising from melanocytes.", "黑色素瘤：源于黑素细胞的危险皮肤癌。", "Early melanoma is highly treatable when caught quickly.", "早期黑色素瘤若及时发现高度可治。", 4, ["melano-", "-oma"]),
        ("psoriasis (plaque)", "/səˈraɪəsɪs/", "A chronic disease causing red, scaly skin plaques.", "银屑病：以红色、鳞屑性皮肤斑块为特征的慢性病。", "Plaque psoriasis often affects the elbows and knees.", "斑块型银屑病常累及肘部和膝部。", 3, ["-osis"]),
    ],
}
