# -*- coding: utf-8 -*-
"""Micro (cellular) seed content: morphemes, vocabulary, and articles.

This is the "医用微观系统" (medical micro system) data — cell biology,
histology, and embryology. gen_seed.py tags every record here with
domain='micro' and resolves morpheme keys against the micro morpheme set only,
so the macro and micro systems stay completely isolated even when a root name
(e.g. cyto-, endo-, -genesis) exists in both.

Vocabulary entry tuple:
(word, ipa, def_en, def_zh, example_en, example_zh, difficulty, [morpheme_keys])
Inner Chinese quotation uses full-width 「」 (ASCII " is the Python delimiter).

Micro category ids (body_systems):
  9  Cell Structure / 细胞结构
  10 Cell Function & Molecular / 细胞功能与分子
  11 Genetics & Molecular Biology / 遗传与分子生物学
  12 Histology / 组织学
  13 Embryology / 胚胎学
"""

# ── Micro morphemes ──────────────────────────────────────────────────────────
# Tuple: (morpheme, type, meaning_zh, meaning_en, origin)
MICRO_MORPHEMES = [
    ("cyto-/-cyte", "root", "细胞", "cell", "Greek"),
    ("karyo-/nucleo-", "root", "细胞核", "nucleus", "Greek/Latin"),
    ("-plasm/plasmo-", "root", "（细胞）质、形成物", "formed material, cytoplasm", "Greek"),
    ("mito-", "root", "线、丝", "thread", "Greek"),
    ("chromo-/chromato-", "root", "颜色（染色质/体）", "color", "Greek"),
    ("-some/somato-", "root", "体", "body", "Greek"),
    ("ribo-", "root", "核糖", "ribose", "English"),
    ("lyso-", "root", "溶解、分解", "dissolution, splitting", "Greek"),
    ("phago-/-phage", "root", "吞噬、进食", "eating, devouring", "Greek"),
    ("pino-", "root", "饮、摄入液体", "drinking", "Greek"),
    ("endo-", "prefix", "内、在……之内", "within, inner", "Greek"),
    ("exo-", "prefix", "外、在……之外", "outside, outer", "Greek"),
    ("ecto-", "prefix", "外、外层", "outer, external", "Greek"),
    ("meso-", "prefix", "中、中间", "middle", "Greek"),
    ("-derm/dermo-", "root", "（胚）层、皮", "layer, skin", "Greek"),
    ("blasto-/-blast", "root", "胚、原始（未成熟）细胞", "germ, immature cell", "Greek"),
    ("gameto-", "root", "生殖细胞、配子", "reproductive cell, gamete", "Greek"),
    ("zygo-", "root", "结合、合", "joined, yoke", "Greek"),
    ("morpho-", "root", "形态", "form, shape", "Greek"),
    ("histo-", "root", "组织", "tissue", "Greek"),
    ("geno-/gen-", "root", "基因、起源", "gene, origin", "Greek"),
    ("-genesis", "suffix", "发生、形成", "origin, formation", "Greek"),
    ("micro-", "prefix", "微、小", "small", "Greek"),
    ("macro-", "prefix", "大、巨", "large", "Greek"),
    ("iso-", "prefix", "等、相同", "equal", "Greek"),
    ("telo-", "root", "末端", "end", "Greek"),
    ("-mere/mero-", "root", "部分、节段", "part", "Greek"),
    ("pro-", "prefix", "前、之前", "before", "Greek"),
    ("meta-", "prefix", "变化、之后", "change, after", "Greek"),
    ("ana-", "prefix", "向上、分开", "up, apart", "Greek"),
    ("auto-", "prefix", "自身", "self", "Greek"),
    ("apo-", "prefix", "离开、脱去", "away, off", "Greek"),
    ("-ptosis", "suffix", "脱落、下降", "falling", "Greek"),
    ("mono-", "prefix", "单、一", "one, single", "Greek"),
    ("di-", "prefix", "二、双", "two", "Greek"),
    ("poly-", "prefix", "多", "many", "Greek"),
    ("-ose", "suffix", "糖", "sugar", "English"),
    ("-ase", "suffix", "酶", "enzyme", "English"),
    ("lipo-", "root", "脂、脂肪", "fat, lipid", "Greek"),
    ("proteo-", "root", "蛋白质", "protein", "Greek"),
    ("glyco-", "root", "糖、葡萄糖", "sugar, glucose", "Greek"),
    ("trans-", "prefix", "跨过、转移", "across, through", "Latin"),
    ("inter-", "prefix", "在……之间", "between", "Latin"),
    ("tono-/-tonic", "root", "张力、渗透压", "tension, tone", "Greek"),
    ("-logy/-ology", "suffix", "……学、研究", "study of", "Greek"),
    ("-osis", "suffix", "状态、过程、异常", "condition, process", "Greek"),
    ("hypo-", "prefix", "低、不足、在……之下", "under, below, deficient", "Greek"),
    ("hyper-", "prefix", "超过、过多、在上", "above, excessive", "Greek"),
    ("-lysis", "suffix", "分解、破坏、溶解", "breakdown, dissolution", "Greek"),
    ("cysto-/-cyst", "root", "囊、膀胱", "sac, bladder", "Greek"),
    ("melano-", "root", "黑色", "black", "Greek"),
]

# ── Micro vocabulary ─────────────────────────────────────────────────────────
MICRO_VOCAB = {
    # ════════════════ System 9 · Cell Structure / 细胞结构 ════════════════
    9: [
        ("cell", "/sel/", "The basic structural and functional unit of all living organisms.", "细胞：一切生物体最基本的结构与功能单位。", "The human body is built from trillions of cells.", "人体由数以万亿计的细胞构成。", 1, []),
        ("cytology", "/saɪˈtɒlədʒi/", "The branch of biology that studies the structure and function of cells.", "细胞学：研究细胞结构与功能的生物学分支。", "Cytology uses microscopes to examine individual cells.", "细胞学借助显微镜检查单个细胞。", 2, ["cyto-", "-logy"]),
        ("organelle", "/ˌɔːrɡəˈnel/", "A specialized structure within a cell that performs a specific function.", "细胞器：细胞内执行特定功能的专门结构。", "The mitochondrion is the organelle that produces most of the cell's energy.", "线粒体是产生细胞大部分能量的细胞器。", 2, []),
        ("nucleus", "/ˈnjuːkliəs/", "The membrane-bound organelle that contains the cell's genetic material.", "细胞核：含有细胞遗传物质的有膜细胞器。", "The nucleus directs the cell's activities through its DNA.", "细胞核通过其 DNA 指挥细胞的活动。", 2, ["karyo-"]),
        ("nucleolus", "/njuːˈkliːələs/", "A dense region within the nucleus where ribosomes are assembled.", "核仁：核内合成核糖体的致密区域。", "The nucleolus produces the RNA and proteins that form ribosomes.", "核仁产生构成核糖体的 RNA 和蛋白质。", 3, ["karyo-"]),
        ("cytoplasm", "/ˈsaɪtoʊplæzəm/", "The gel-like substance enclosed by the cell membrane, excluding the nucleus.", "细胞质：细胞膜内除细胞核以外的凝胶状物质。", "Most metabolic reactions take place in the cytoplasm.", "大多数代谢反应发生在细胞质中。", 2, ["cyto-", "-plasm"]),
        ("cytosol", "/ˈsaɪtoʊsɒl/", "The fluid portion of the cytoplasm in which organelles are suspended.", "胞质溶胶：细胞质中悬浮各种细胞器的液体部分。", "Glycolysis occurs in the cytosol.", "糖酵解发生在胞质溶胶中。", 3, ["cyto-"]),
        ("plasma membrane", "/ˈplæzmə ˈmembreɪn/", "The thin barrier that surrounds the cell and controls what enters and leaves.", "质膜（细胞膜）：包绕细胞、控制物质进出的薄屏障。", "The plasma membrane is made of a phospholipid bilayer.", "质膜由磷脂双分子层构成。", 2, []),
        ("phospholipid", "/ˌfɒsfoʊˈlɪpɪd/", "A lipid molecule that forms the double layer of cell membranes.", "磷脂：构成细胞膜双分子层的脂质分子。", "Each phospholipid has a water-loving head and water-fearing tails.", "每个磷脂分子具有亲水的头部和疏水的尾部。", 3, ["lipo-"]),
        ("glycocalyx", "/ˌɡlaɪkoʊˈkeɪlɪks/", "The sugar-rich coating on the outer surface of the cell membrane.", "糖萼：细胞膜外表面富含糖类的包被。", "The glycocalyx helps cells recognize one another.", "糖萼有助于细胞之间相互识别。", 4, ["glyco-"]),
        ("mitochondrion", "/ˌmaɪtoʊˈkɒndriən/", "The organelle that generates most of the cell's ATP through respiration.", "线粒体：通过呼吸作用产生细胞大部分 ATP 的细胞器。", "Cells with high energy needs contain many mitochondria.", "能量需求高的细胞含有大量线粒体。", 3, ["mito-"]),
        ("cristae", "/ˈkrɪstiː/", "The inner folds of the mitochondrial membrane where ATP is made.", "嵴：线粒体内膜的褶皱，是生成 ATP 的部位。", "The cristae increase the surface area for energy production.", "嵴增大了能量生产的表面积。", 4, []),
        ("ribosome", "/ˈraɪbəsoʊm/", "The cellular structure that builds proteins by linking amino acids.", "核糖体：通过连接氨基酸合成蛋白质的细胞结构。", "Ribosomes read messenger RNA to assemble proteins.", "核糖体读取信使 RNA 来组装蛋白质。", 3, ["ribo-", "-some"]),
        ("endoplasmic reticulum", "/ˌendoʊˈplæzmɪk rɪˈtɪkjələm/", "A network of membranes that makes proteins and lipids.", "内质网：合成蛋白质和脂质的膜网状系统。", "Rough endoplasmic reticulum is studded with ribosomes.", "粗面内质网表面附着核糖体。", 4, ["endo-", "-plasm"]),
        ("Golgi apparatus", "/ˈɡɔːldʒi ˌæpəˈreɪtəs/", "The organelle that modifies, sorts, and packages proteins for export.", "高尔基体：对蛋白质进行修饰、分选和包装以供输出的细胞器。", "The Golgi apparatus packages proteins into vesicles.", "高尔基体将蛋白质包装入囊泡。", 4, []),
        ("lysosome", "/ˈlaɪsəsoʊm/", "An organelle filled with enzymes that digest waste and worn-out parts.", "溶酶体：含有消化废物和老化结构的酶的细胞器。", "Lysosomes break down material brought in by the cell.", "溶酶体分解细胞摄入的物质。", 3, ["lyso-", "-some"]),
        ("peroxisome", "/pəˈrɒksɪsoʊm/", "An organelle that breaks down fatty acids and detoxifies harmful substances.", "过氧化物酶体：分解脂肪酸并对有害物质解毒的细胞器。", "Peroxisomes neutralize hydrogen peroxide in the cell.", "过氧化物酶体可中和细胞内的过氧化氢。", 4, ["-some"]),
        ("vacuole", "/ˈvækjuoʊl/", "A membrane-bound sac used for storage of water, nutrients, or waste.", "液泡：用于储存水分、养分或废物的有膜囊。", "Vacuoles help maintain the cell's internal pressure.", "液泡有助于维持细胞的内部压力。", 3, []),
        ("vesicle", "/ˈvesɪkəl/", "A small membrane sac that transports materials within or out of the cell.", "囊泡：在细胞内或向细胞外运输物质的小膜囊。", "Transport vesicles carry proteins to the cell membrane.", "运输囊泡将蛋白质送往细胞膜。", 3, []),
        ("centriole", "/ˈsentrioʊl/", "A cylindrical structure that helps organize the spindle during cell division.", "中心粒：在细胞分裂时帮助组织纺锤体的圆柱状结构。", "Centrioles move to opposite poles before mitosis.", "中心粒在有丝分裂前移向两极。", 4, []),
        ("centrosome", "/ˈsentrəsoʊm/", "The region near the nucleus that organizes microtubules.", "中心体：核附近组织微管的区域。", "The centrosome contains a pair of centrioles.", "中心体含有一对中心粒。", 4, ["-some"]),
        ("cytoskeleton", "/ˌsaɪtoʊˈskelɪtən/", "The network of protein fibers that gives a cell its shape and support.", "细胞骨架：赋予细胞形状和支撑的蛋白纤维网络。", "The cytoskeleton enables cell movement and division.", "细胞骨架使细胞能够运动和分裂。", 3, ["cyto-"]),
        ("microtubule", "/ˌmaɪkroʊˈtjuːbjuːl/", "A hollow protein tube that supports the cell and guides transport.", "微管：支撑细胞并引导物质运输的中空蛋白管。", "Microtubules form the tracks along which vesicles travel.", "微管形成囊泡移动的轨道。", 4, ["micro-"]),
        ("microfilament", "/ˌmaɪkroʊˈfɪləmənt/", "A thin actin fiber involved in cell shape and movement.", "微丝：参与细胞形态和运动的细肌动蛋白纤维。", "Microfilaments allow the cell to change shape.", "微丝使细胞能够改变形状。", 4, ["micro-"]),
        ("intermediate filament", "/ˌɪntərˈmiːdiət ˈfɪləmənt/", "A rope-like fiber that provides mechanical strength to cells.", "中间丝：为细胞提供机械强度的绳索状纤维。", "Intermediate filaments anchor organelles in place.", "中间丝将细胞器固定在适当位置。", 4, ["inter-"]),
        ("chromatin", "/ˈkroʊmətɪn/", "The loosely packed combination of DNA and proteins inside the nucleus.", "染色质：细胞核内 DNA 与蛋白质疏松结合的形式。", "Chromatin condenses into chromosomes before cell division.", "染色质在细胞分裂前凝缩为染色体。", 3, ["chromo-"]),
        ("chromosome", "/ˈkroʊməsoʊm/", "A condensed structure of DNA that carries genetic information.", "染色体：携带遗传信息的 DNA 凝缩结构。", "Humans normally have 46 chromosomes in each cell.", "人体每个细胞通常有 46 条染色体。", 2, ["chromo-", "-some"]),
        ("nuclear envelope", "/ˈnjuːkliər ˈenvəloʊp/", "The double membrane that surrounds and protects the nucleus.", "核膜：包绕并保护细胞核的双层膜。", "The nuclear envelope separates DNA from the cytoplasm.", "核膜将 DNA 与细胞质分隔开。", 4, ["karyo-"]),
        ("nuclear pore", "/ˈnjuːkliər pɔːr/", "A channel in the nuclear envelope that lets molecules pass in and out.", "核孔：核膜上允许分子进出的通道。", "Messenger RNA leaves the nucleus through nuclear pores.", "信使 RNA 通过核孔离开细胞核。", 4, ["karyo-"]),
        ("cilium", "/ˈsɪliəm/", "A short hair-like projection that moves fluid or particles across a cell surface.", "纤毛：细胞表面短小的毛状突起，可推动液体或颗粒。", "Cilia in the airways sweep mucus upward.", "气道中的纤毛将黏液向上清扫。", 3, []),
        ("flagellum", "/fləˈdʒeləm/", "A long whip-like structure that propels a cell.", "鞭毛：推动细胞运动的细长鞭状结构。", "A sperm cell swims using its flagellum.", "精子借助鞭毛游动。", 3, []),
        ("microvillus", "/ˌmaɪkroʊˈvɪləs/", "A tiny finger-like projection that increases a cell's surface area.", "微绒毛：增大细胞表面积的微小指状突起。", "Microvilli line the small intestine to aid absorption.", "微绒毛排列于小肠以促进吸收。", 4, ["micro-"]),
        ("eukaryote", "/juːˈkærioʊt/", "An organism whose cells contain a true membrane-bound nucleus.", "真核生物：细胞含有真正有膜细胞核的生物。", "Animals, plants, and fungi are all eukaryotes.", "动物、植物和真菌都是真核生物。", 4, ["karyo-"]),
        ("prokaryote", "/proʊˈkærioʊt/", "An organism whose cells lack a membrane-bound nucleus, such as bacteria.", "原核生物：细胞缺乏有膜细胞核的生物，如细菌。", "Bacteria are prokaryotes with no internal organelles.", "细菌是没有内膜细胞器的原核生物。", 4, ["pro-", "karyo-"]),
        ("cytoplasmic membrane", "/ˌsaɪtoʊˈplæzmɪk ˈmembreɪn/", "Another name for the plasma membrane surrounding the cytoplasm.", "胞质膜：包绕细胞质的质膜的别称。", "The cytoplasmic membrane regulates the cell's internal environment.", "胞质膜调节细胞的内环境。", 4, ["cyto-", "-plasm"]),
        ("inclusion", "/ɪnˈkluːʒən/", "A non-living particle stored in the cytoplasm, such as glycogen or fat.", "包涵物：储存于细胞质中的非生命颗粒，如糖原或脂肪。", "Lipid inclusions store energy within the cell.", "脂质包涵物在细胞内储存能量。", 4, []),
        ("cell junction", "/sel ˈdʒʌŋkʃən/", "A point of contact that connects neighboring cells.", "细胞连接：连接相邻细胞的接触点。", "Tight cell junctions seal the gaps between intestinal cells.", "紧密细胞连接封闭肠细胞之间的间隙。", 4, []),
        ("phagocyte", "/ˈfæɡəsaɪt/", "A cell that engulfs and digests particles or microbes.", "吞噬细胞：吞入并消化颗粒或微生物的细胞。", "Phagocytes are an important part of the immune defense.", "吞噬细胞是免疫防御的重要组成部分。", 3, ["phago-", "-cyte"]),
    ],
    # ════════════════ System 10 · Cell Function & Molecular / 细胞功能与分子 ════
    10: [
        ("diffusion", "/dɪˈfjuːʒən/", "The movement of molecules from high to low concentration.", "扩散：分子从高浓度向低浓度移动的过程。", "Oxygen enters cells by diffusion across the membrane.", "氧气通过跨膜扩散进入细胞。", 2, []),
        ("osmosis", "/ɒzˈmoʊsɪs/", "The diffusion of water across a selectively permeable membrane.", "渗透：水分子跨选择性通透膜的扩散。", "Osmosis moves water toward the side with more solute.", "渗透使水向溶质更多的一侧移动。", 3, ["-osis"]),
        ("passive transport", "/ˈpæsɪv ˈtrænspɔːrt/", "Movement of substances across a membrane without using energy.", "被动运输：物质不消耗能量跨膜移动。", "Passive transport follows the concentration gradient.", "被动运输顺浓度梯度进行。", 3, ["trans-"]),
        ("active transport", "/ˈæktɪv ˈtrænspɔːrt/", "Movement of substances across a membrane using cellular energy.", "主动运输：物质消耗细胞能量逆向跨膜移动。", "Active transport can move ions against their gradient.", "主动运输可使离子逆浓度梯度移动。", 3, ["trans-"]),
        ("facilitated diffusion", "/fəˈsɪlɪteɪtɪd dɪˈfjuːʒən/", "Passive movement of molecules through membrane proteins.", "易化扩散：分子借助膜蛋白进行的被动移动。", "Glucose enters many cells by facilitated diffusion.", "葡萄糖通过易化扩散进入许多细胞。", 4, []),
        ("endocytosis", "/ˌendoʊsaɪˈtoʊsɪs/", "The process by which a cell takes in material by engulfing it.", "胞吞作用：细胞通过包裹方式摄入物质的过程。", "Endocytosis brings large particles into the cell.", "胞吞作用将大颗粒带入细胞。", 4, ["endo-", "cyto-", "-osis"]),
        ("exocytosis", "/ˌeksoʊsaɪˈtoʊsɪs/", "The process by which a cell releases material in vesicles.", "胞吐作用：细胞以囊泡形式向外释放物质的过程。", "Neurons use exocytosis to release neurotransmitters.", "神经元通过胞吐作用释放神经递质。", 4, ["exo-", "cyto-", "-osis"]),
        ("phagocytosis", "/ˌfæɡoʊsaɪˈtoʊsɪs/", "The engulfing of large particles or cells by a cell.", "吞噬作用：细胞吞入大颗粒或其他细胞。", "White blood cells destroy bacteria by phagocytosis.", "白细胞通过吞噬作用消灭细菌。", 4, ["phago-", "cyto-", "-osis"]),
        ("pinocytosis", "/ˌpɪnoʊsaɪˈtoʊsɪs/", "The uptake of fluid and dissolved substances by a cell.", "胞饮作用：细胞摄入液体及其中溶解物质的过程。", "Pinocytosis is sometimes called cell drinking.", "胞饮作用有时被称为「细胞饮水」。", 4, ["pino-", "cyto-", "-osis"]),
        ("ion channel", "/ˈaɪɒn ˈtʃænəl/", "A membrane protein that lets specific ions pass through.", "离子通道：允许特定离子通过的膜蛋白。", "Ion channels open and close to control ion flow.", "离子通道通过开闭来控制离子流动。", 4, []),
        ("carrier protein", "/ˈkæriər ˈproʊtiːn/", "A membrane protein that binds and moves molecules across the membrane.", "载体蛋白：结合并转运分子跨膜的膜蛋白。", "Carrier proteins change shape to move glucose inward.", "载体蛋白通过改变构象将葡萄糖运入细胞。", 4, ["proteo-"]),
        ("concentration gradient", "/ˌkɒnsənˈtreɪʃən ˈɡreɪdiənt/", "A difference in the amount of a substance between two regions.", "浓度梯度：某物质在两个区域之间的含量差异。", "Molecules diffuse down a concentration gradient.", "分子顺浓度梯度扩散。", 3, []),
        ("isotonic", "/ˌaɪsoʊˈtɒnɪk/", "Having the same solute concentration as another solution.", "等渗的：与另一溶液溶质浓度相同。", "Cells keep their normal shape in an isotonic solution.", "细胞在等渗溶液中保持正常形态。", 4, ["iso-", "-tonic"]),
        ("hypotonic", "/ˌhaɪpoʊˈtɒnɪk/", "Having a lower solute concentration than another solution.", "低渗的：溶质浓度低于另一溶液。", "A cell in a hypotonic solution swells as water enters.", "细胞在低渗溶液中因水分进入而肿胀。", 4, ["hypo-", "-tonic"]),
        ("hypertonic", "/ˌhaɪpərˈtɒnɪk/", "Having a higher solute concentration than another solution.", "高渗的：溶质浓度高于另一溶液。", "A cell in a hypertonic solution shrinks as water leaves.", "细胞在高渗溶液中因水分流失而皱缩。", 4, ["hyper-", "-tonic"]),
        ("membrane potential", "/ˈmembreɪn pəˈtenʃəl/", "The voltage difference across a cell's membrane.", "膜电位：细胞膜两侧的电压差。", "Nerve cells use changes in membrane potential to signal.", "神经细胞利用膜电位的变化传递信号。", 4, []),
        ("ATP", "/ˌeɪ tiː ˈpiː/", "Adenosine triphosphate, the main energy-carrying molecule of cells.", "ATP（三磷酸腺苷）：细胞主要的能量载体分子。", "ATP releases energy when one of its phosphate bonds breaks.", "ATP 在一个磷酸键断裂时释放能量。", 3, []),
        ("metabolism", "/məˈtæbəlɪzəm/", "All the chemical reactions that occur within a cell or organism.", "代谢：细胞或机体内发生的全部化学反应。", "Metabolism includes both building and breaking down molecules.", "代谢既包括合成也包括分解分子。", 2, ["meta-"]),
        ("anabolism", "/əˈnæbəlɪzəm/", "The metabolic building of complex molecules from simpler ones.", "合成代谢：由简单分子构建复杂分子的代谢过程。", "Anabolism requires energy to build tissues.", "合成代谢需要能量来构建组织。", 4, ["ana-"]),
        ("catabolism", "/kəˈtæbəlɪzəm/", "The metabolic breakdown of molecules to release energy.", "分解代谢：分解分子以释放能量的代谢过程。", "Catabolism breaks glucose down to release ATP.", "分解代谢分解葡萄糖以释放 ATP。", 4, []),
        ("enzyme", "/ˈenzaɪm/", "A protein that speeds up a specific chemical reaction.", "酶：加速特定化学反应的蛋白质。", "Each enzyme acts on a particular substrate.", "每种酶作用于特定的底物。", 3, []),
        ("substrate", "/ˈsʌbstreɪt/", "The molecule on which an enzyme acts.", "底物：酶所作用的分子。", "The substrate binds to the active site of the enzyme.", "底物结合到酶的活性位点。", 3, []),
        ("glycolysis", "/ɡlaɪˈkɒlɪsɪs/", "The breakdown of glucose into pyruvate, releasing some energy.", "糖酵解：将葡萄糖分解为丙酮酸并释放少量能量的过程。", "Glycolysis takes place in the cytosol without oxygen.", "糖酵解在胞质溶胶中无氧条件下进行。", 4, ["glyco-", "-lysis"]),
        ("cellular respiration", "/ˈseljələr ˌrespəˈreɪʃən/", "The process that converts nutrients into ATP using oxygen.", "细胞呼吸：利用氧气将养分转化为 ATP 的过程。", "Cellular respiration mostly occurs in the mitochondria.", "细胞呼吸主要在线粒体内进行。", 4, []),
        ("oxidative phosphorylation", "/ˈɒksɪdeɪtɪv ˌfɒsfɔːrɪˈleɪʃən/", "The mitochondrial process that produces most ATP using oxygen.", "氧化磷酸化：线粒体利用氧气生成大部分 ATP 的过程。", "Oxidative phosphorylation yields far more ATP than glycolysis.", "氧化磷酸化产生的 ATP 远多于糖酵解。", 5, []),
        ("signal transduction", "/ˈsɪɡnəl trænzˈdʌkʃən/", "The relay of a signal from outside the cell to a response inside.", "信号转导：将细胞外信号传递为细胞内反应的过程。", "Signal transduction lets hormones change a cell's behavior.", "信号转导使激素能够改变细胞的行为。", 5, ["trans-"]),
        ("receptor", "/rɪˈseptər/", "A protein that binds a specific molecule and triggers a response.", "受体：结合特定分子并引发反应的蛋白质。", "A hormone must fit its receptor like a key in a lock.", "激素必须像钥匙配锁那样与其受体匹配。", 3, []),
        ("ligand", "/ˈlɪɡənd/", "A molecule that binds to a receptor to produce an effect.", "配体：与受体结合以产生效应的分子。", "When a ligand binds, the receptor changes shape.", "配体结合时，受体随之改变构象。", 4, []),
        ("apoptosis", "/ˌæpəpˈtoʊsɪs/", "Programmed cell death that removes unwanted or damaged cells.", "细胞凋亡：清除不需要或受损细胞的程序性细胞死亡。", "Apoptosis shapes tissues during development.", "细胞凋亡在发育过程中塑造组织。", 5, ["apo-", "-ptosis"]),
        ("autophagy", "/ɔːˈtɒfədʒi/", "The process by which a cell digests its own worn-out components.", "自噬：细胞消化自身老化组分的过程。", "Autophagy recycles damaged organelles for reuse.", "自噬将受损细胞器回收再利用。", 5, ["auto-", "phago-"]),
        ("cell cycle", "/sel ˈsaɪkəl/", "The ordered series of stages a cell passes through to divide.", "细胞周期：细胞为分裂而经历的有序阶段序列。", "The cell cycle includes interphase and mitosis.", "细胞周期包括间期和有丝分裂。", 3, []),
        ("interphase", "/ˈɪntərfeɪz/", "The phase of the cell cycle when a cell grows and copies its DNA.", "间期：细胞生长并复制 DNA 的细胞周期阶段。", "A cell spends most of its life in interphase.", "细胞一生大部分时间处于间期。", 3, ["inter-"]),
        ("mitosis", "/maɪˈtoʊsɪs/", "The division of the nucleus that produces two identical cells.", "有丝分裂：产生两个完全相同细胞的核分裂过程。", "Mitosis allows the body to grow and replace cells.", "有丝分裂使机体得以生长并替换细胞。", 4, ["mito-", "-osis"]),
        ("cytokinesis", "/ˌsaɪtoʊkɪˈniːsɪs/", "The division of the cytoplasm that completes cell division.", "胞质分裂：完成细胞分裂的细胞质分裂过程。", "Cytokinesis splits one cell into two daughter cells.", "胞质分裂将一个细胞分为两个子细胞。", 4, ["cyto-"]),
        ("prophase", "/ˈproʊfeɪz/", "The first stage of mitosis, when chromosomes condense.", "前期：有丝分裂的第一阶段，染色体凝缩。", "During prophase the spindle fibers begin to form.", "前期纺锤丝开始形成。", 4, ["pro-"]),
        ("metaphase", "/ˈmetəfeɪz/", "The stage of mitosis when chromosomes line up at the cell's center.", "中期：染色体排列在细胞中央的有丝分裂阶段。", "In metaphase the chromosomes align along the equator.", "中期染色体沿赤道板排列。", 4, ["meta-"]),
        ("anaphase", "/ˈænəfeɪz/", "The stage of mitosis when sister chromatids separate.", "后期：姐妹染色单体分离的有丝分裂阶段。", "Anaphase pulls the chromatids to opposite poles.", "后期将染色单体拉向两极。", 4, ["ana-"]),
        ("telophase", "/ˈteləfeɪz/", "The final stage of mitosis, when two new nuclei form.", "末期：有丝分裂的最后阶段，形成两个新核。", "By telophase the nuclear envelope reappears.", "到末期核膜重新出现。", 4, ["telo-"]),
    ],
    # ════════════════ System 11 · Genetics & Molecular Biology / 遗传与分子生物学 ═
    11: [
        ("DNA", "/ˌdiː en ˈeɪ/", "Deoxyribonucleic acid, the molecule that stores genetic information.", "DNA（脱氧核糖核酸）：储存遗传信息的分子。", "DNA is shaped like a twisted ladder called a double helix.", "DNA 呈称为双螺旋的扭曲梯状结构。", 2, []),
        ("RNA", "/ˌɑːr en ˈeɪ/", "Ribonucleic acid, a molecule that helps carry out genetic instructions.", "RNA（核糖核酸）：协助执行遗传指令的分子。", "RNA carries the message from DNA to the ribosome.", "RNA 将信息从 DNA 带到核糖体。", 2, ["ribo-"]),
        ("nucleotide", "/ˈnjuːkliətaɪd/", "The basic building block of DNA and RNA.", "核苷酸：DNA 和 RNA 的基本结构单元。", "Each nucleotide contains a sugar, a phosphate, and a base.", "每个核苷酸含有一个糖、一个磷酸和一个碱基。", 4, ["karyo-"]),
        ("nucleic acid", "/njuːˈkleɪɪk ˈæsɪd/", "A large molecule, such as DNA or RNA, made of nucleotides.", "核酸：由核苷酸构成的大分子，如 DNA 或 RNA。", "Nucleic acids store and transmit genetic information.", "核酸储存并传递遗传信息。", 4, ["karyo-"]),
        ("gene", "/dʒiːn/", "A segment of DNA that codes for a particular protein or trait.", "基因：编码特定蛋白质或性状的 DNA 片段。", "A single gene can determine eye color.", "单个基因即可决定眼睛的颜色。", 2, ["geno-"]),
        ("genome", "/ˈdʒiːnoʊm/", "The complete set of genetic material in an organism.", "基因组：一个生物体全部遗传物质的总和。", "The human genome contains about 20,000 genes.", "人类基因组约含两万个基因。", 4, ["geno-"]),
        ("allele", "/əˈliːl/", "One of the alternative forms of a gene.", "等位基因：一个基因的不同形式之一。", "A person inherits one allele of each gene from each parent.", "每个基因的一个等位基因分别来自父母双方。", 4, []),
        ("chromatid", "/ˈkroʊmətɪd/", "One of the two identical halves of a duplicated chromosome.", "染色单体：已复制染色体的两个相同部分之一。", "Sister chromatids are joined at the centromere.", "姐妹染色单体在着丝粒处相连。", 4, ["chromo-"]),
        ("centromere", "/ˈsentrəmɪr/", "The region that joins two sister chromatids together.", "着丝粒：连接两条姐妹染色单体的区域。", "Spindle fibers attach to the chromosome at the centromere.", "纺锤丝在着丝粒处与染色体相连。", 4, ["-mere"]),
        ("telomere", "/ˈteləmɪr/", "A protective cap at the end of a chromosome.", "端粒：染色体末端的保护性结构。", "Telomeres shorten each time a cell divides.", "细胞每分裂一次，端粒就缩短一些。", 5, ["telo-", "-mere"]),
        ("codon", "/ˈkoʊdɒn/", "A sequence of three bases that codes for one amino acid.", "密码子：编码一个氨基酸的三个碱基序列。", "Each codon on mRNA specifies a single amino acid.", "mRNA 上的每个密码子指定一个氨基酸。", 4, []),
        ("transcription", "/trænˈskrɪpʃən/", "The process of copying DNA into messenger RNA.", "转录：将 DNA 拷贝为信使 RNA 的过程。", "Transcription takes place inside the nucleus.", "转录在细胞核内进行。", 4, ["trans-"]),
        ("translation", "/trænzˈleɪʃən/", "The process of building a protein from a messenger RNA sequence.", "翻译：依据信使 RNA 序列合成蛋白质的过程。", "Translation occurs on ribosomes in the cytoplasm.", "翻译在细胞质的核糖体上进行。", 4, ["trans-"]),
        ("replication", "/ˌreplɪˈkeɪʃən/", "The copying of a DNA molecule before cell division.", "复制：细胞分裂前对 DNA 分子的拷贝。", "DNA replication ensures each new cell gets a full copy.", "DNA 复制确保每个新细胞都获得完整拷贝。", 4, []),
        ("mutation", "/mjuːˈteɪʃən/", "A change in the DNA sequence of a gene.", "突变：基因 DNA 序列的改变。", "A mutation can alter the protein a gene produces.", "突变可改变基因所产生的蛋白质。", 3, []),
        ("messenger RNA", "/ˈmesɪndʒər ˌɑːr en ˈeɪ/", "The RNA that carries genetic instructions from DNA to the ribosome.", "信使 RNA：将遗传指令从 DNA 带到核糖体的 RNA。", "Messenger RNA is read in groups of three bases.", "信使 RNA 以每三个碱基为一组被读取。", 4, ["ribo-"]),
        ("transfer RNA", "/ˈtrænsfɜːr ˌɑːr en ˈeɪ/", "The RNA that brings amino acids to the ribosome during translation.", "转运 RNA：翻译时将氨基酸带到核糖体的 RNA。", "Each transfer RNA carries one specific amino acid.", "每个转运 RNA 携带一种特定氨基酸。", 4, ["trans-", "ribo-"]),
        ("ribosomal RNA", "/ˌraɪbəˈsoʊməl ˌɑːr en ˈeɪ/", "The RNA that forms part of the structure of ribosomes.", "核糖体 RNA：构成核糖体结构一部分的 RNA。", "Ribosomal RNA helps catalyze protein assembly.", "核糖体 RNA 协助催化蛋白质组装。", 5, ["ribo-", "-some"]),
        ("polymerase", "/pəˈlɪməreɪs/", "An enzyme that builds nucleic acids by linking nucleotides.", "聚合酶：通过连接核苷酸合成核酸的酶。", "DNA polymerase adds new bases during replication.", "DNA 聚合酶在复制时添加新碱基。", 5, ["poly-", "-ase"]),
        ("helicase", "/ˈhelɪkeɪs/", "An enzyme that unwinds the DNA double helix.", "解旋酶：解开 DNA 双螺旋的酶。", "Helicase separates the two DNA strands for copying.", "解旋酶将两条 DNA 链分开以供复制。", 5, ["-ase"]),
        ("base pair", "/beɪs peər/", "Two complementary bases joined across the DNA strands.", "碱基对：DNA 两条链间互补配对的两个碱基。", "Adenine and thymine form one base pair.", "腺嘌呤与胸腺嘧啶组成一个碱基对。", 4, []),
        ("double helix", "/ˈdʌbəl ˈhiːlɪks/", "The twisted-ladder shape of the DNA molecule.", "双螺旋：DNA 分子的扭曲梯状结构。", "Watson and Crick described DNA's double helix in 1953.", "沃森和克里克于 1953 年描述了 DNA 的双螺旋。", 4, []),
        ("genotype", "/ˈdʒiːnoʊtaɪp/", "The genetic makeup of an organism.", "基因型：生物体的遗传组成。", "Genotype interacts with the environment to shape traits.", "基因型与环境相互作用塑造性状。", 4, ["geno-"]),
        ("phenotype", "/ˈfiːnoʊtaɪp/", "The observable characteristics of an organism.", "表型：生物体可观察到的性状特征。", "Height is a phenotype influenced by many genes.", "身高是受许多基因影响的表型。", 4, []),
        ("dominant", "/ˈdɒmɪnənt/", "Describing an allele that is expressed even when only one copy is present.", "显性的：只需一个拷贝即可表达的等位基因。", "Brown eye color is a dominant trait.", "棕色眼睛是显性性状。", 3, []),
        ("recessive", "/rɪˈsesɪv/", "Describing an allele expressed only when two copies are present.", "隐性的：需两个拷贝才能表达的等位基因。", "A recessive trait appears only without a dominant allele.", "隐性性状只有在没有显性等位基因时才出现。", 3, []),
        ("heterozygous", "/ˌhetəroʊˈzaɪɡəs/", "Having two different alleles for a particular gene.", "杂合的：某基因具有两个不同等位基因。", "A heterozygous individual carries one of each allele.", "杂合个体各携带一个不同的等位基因。", 5, ["zygo-"]),
        ("homozygous", "/ˌhoʊmoʊˈzaɪɡəs/", "Having two identical alleles for a particular gene.", "纯合的：某基因具有两个相同等位基因。", "A homozygous plant breeds true for that trait.", "纯合植株在该性状上能稳定遗传。", 5, ["zygo-"]),
        ("diploid", "/ˈdɪplɔɪd/", "Having two complete sets of chromosomes.", "二倍体：具有两套完整染色体。", "Human body cells are diploid, with 46 chromosomes.", "人体体细胞为二倍体，含 46 条染色体。", 4, ["di-"]),
        ("haploid", "/ˈhæplɔɪd/", "Having a single set of chromosomes, as in gametes.", "单倍体：仅有一套染色体，如配子。", "Sperm and egg cells are haploid.", "精子和卵细胞为单倍体。", 4, []),
        ("gene expression", "/dʒiːn ɪkˈspreʃən/", "The process by which a gene's information is used to make a product.", "基因表达：利用基因信息生成产物的过程。", "Gene expression determines which proteins a cell makes.", "基因表达决定细胞制造哪些蛋白质。", 4, ["geno-"]),
        ("polypeptide", "/ˌpɒliˈpeptaɪd/", "A chain of many amino acids linked together.", "多肽：由许多氨基酸连接而成的链。", "A protein may be made of one or more polypeptides.", "一种蛋白质可由一条或多条多肽构成。", 4, ["poly-"]),
        ("amino acid", "/əˈmiːnoʊ ˈæsɪd/", "The building block of proteins.", "氨基酸：蛋白质的结构单元。", "There are twenty common amino acids in proteins.", "蛋白质中常见的氨基酸有二十种。", 3, []),
        ("protein synthesis", "/ˈproʊtiːn ˈsɪnθəsɪs/", "The cellular process of building proteins from amino acids.", "蛋白质合成：细胞由氨基酸构建蛋白质的过程。", "Protein synthesis involves transcription and translation.", "蛋白质合成包括转录和翻译。", 4, ["proteo-"]),
        ("monomer", "/ˈmɒnəmər/", "A small molecule that can join others to form a polymer.", "单体：能与其他分子连接形成聚合物的小分子。", "Glucose is the monomer that makes up starch.", "葡萄糖是构成淀粉的单体。", 4, ["mono-", "-mere"]),
        ("polymer", "/ˈpɒlɪmər/", "A large molecule made of many repeating subunits.", "聚合物：由许多重复亚基构成的大分子。", "DNA is a polymer of nucleotides.", "DNA 是核苷酸的聚合物。", 4, ["poly-", "-mere"]),
        ("deoxyribose", "/diˌɒksɪˈraɪboʊs/", "The five-carbon sugar found in DNA.", "脱氧核糖：DNA 中的五碳糖。", "Deoxyribose forms the backbone of the DNA strand.", "脱氧核糖构成 DNA 链的骨架。", 5, ["ribo-", "-ose"]),
    ],
    # ════════════════ System 12 · Histology / 组织学 ════════════════
    12: [
        ("tissue", "/ˈtɪʃuː/", "A group of similar cells that work together to perform a function.", "组织：一群协同执行某种功能的相似细胞。", "Muscle is a tissue specialized for contraction.", "肌肉是专门用于收缩的组织。", 2, ["histo-"]),
        ("histology", "/hɪˈstɒlədʒi/", "The microscopic study of the structure of tissues.", "组织学：在显微镜下研究组织结构的学科。", "Histology reveals how cells are arranged within a tissue.", "组织学揭示细胞在组织内的排列方式。", 2, ["histo-", "-logy"]),
        ("epithelium", "/ˌepɪˈθiːliəm/", "The tissue that covers body surfaces and lines cavities.", "上皮：覆盖体表并衬于体腔内表面的组织。", "The epithelium of the skin protects against water loss.", "皮肤的上皮可防止水分流失。", 3, []),
        ("epithelial tissue", "/ˌepɪˈθiːliəl ˈtɪʃuː/", "A tissue type forming protective layers and linings.", "上皮组织：形成保护性覆盖层和衬里的组织类型。", "Epithelial tissue lines the digestive tract.", "上皮组织衬于消化道内表面。", 3, ["histo-"]),
        ("connective tissue", "/kəˈnektɪv ˈtɪʃuː/", "A tissue that supports, binds, or separates other tissues.", "结缔组织：支持、连接或分隔其他组织的组织。", "Bone and blood are types of connective tissue.", "骨和血液都属于结缔组织。", 3, ["histo-"]),
        ("muscle tissue", "/ˈmʌsəl ˈtɪʃuː/", "A tissue specialized to contract and produce movement.", "肌组织：专门用于收缩并产生运动的组织。", "Muscle tissue can be skeletal, cardiac, or smooth.", "肌组织可分为骨骼肌、心肌和平滑肌。", 3, ["histo-"]),
        ("nervous tissue", "/ˈnɜːrvəs ˈtɪʃuː/", "A tissue that transmits electrical signals through the body.", "神经组织：在体内传导电信号的组织。", "Nervous tissue makes up the brain and nerves.", "神经组织构成脑和神经。", 3, ["histo-"]),
        ("squamous", "/ˈskweɪməs/", "Describing flat, scale-like epithelial cells.", "鳞状的：形容扁平、鳞片状的上皮细胞。", "Squamous cells line the air sacs of the lungs.", "鳞状细胞衬于肺的气囊内表面。", 4, []),
        ("cuboidal", "/kjuːˈbɔɪdəl/", "Describing cube-shaped epithelial cells.", "立方的：形容立方体形状的上皮细胞。", "Cuboidal cells line many glands and kidney tubules.", "立方细胞衬于许多腺体和肾小管。", 4, []),
        ("columnar", "/kəˈlʌmnər/", "Describing tall, column-shaped epithelial cells.", "柱状的：形容高柱形的上皮细胞。", "Columnar cells absorb nutrients in the intestine.", "柱状细胞在肠道吸收养分。", 4, []),
        ("basement membrane", "/ˈbeɪsmənt ˈmembreɪn/", "A thin layer that anchors epithelium to underlying tissue.", "基膜：将上皮固定于下层组织的薄层。", "The basement membrane supports the epithelial cells above it.", "基膜支撑其上方的上皮细胞。", 4, []),
        ("gland", "/ɡlænd/", "A structure that produces and releases a substance.", "腺体：产生并释放某种物质的结构。", "A sweat gland releases fluid onto the skin.", "汗腺将液体释放到皮肤表面。", 2, []),
        ("exocrine gland", "/ˈeksoʊkrɪn ɡlænd/", "A gland that releases its product through a duct.", "外分泌腺：通过导管释放分泌物的腺体。", "Salivary glands are exocrine glands.", "唾液腺属于外分泌腺。", 4, ["exo-"]),
        ("endocrine gland", "/ˈendoʊkrɪn ɡlænd/", "A gland that releases hormones directly into the blood.", "内分泌腺：将激素直接释放入血的腺体。", "The thyroid is an endocrine gland.", "甲状腺是一种内分泌腺。", 4, ["endo-"]),
        ("collagen", "/ˈkɒlədʒən/", "A strong fibrous protein that gives connective tissue strength.", "胶原蛋白：赋予结缔组织强度的强韧纤维蛋白。", "Collagen provides tensile strength to tendons.", "胶原蛋白为肌腱提供抗拉强度。", 3, ["proteo-"]),
        ("elastin", "/ɪˈlæstɪn/", "A protein that lets tissues stretch and return to shape.", "弹性蛋白：使组织能够伸展并回弹的蛋白质。", "Elastin makes skin and arteries flexible.", "弹性蛋白使皮肤和动脉富有弹性。", 4, ["proteo-"]),
        ("fibroblast", "/ˈfaɪbroʊblæst/", "A connective tissue cell that produces collagen and fibers.", "成纤维细胞：产生胶原和纤维的结缔组织细胞。", "Fibroblasts help wounds heal by laying down new matrix.", "成纤维细胞通过铺设新基质帮助伤口愈合。", 4, ["-blast"]),
        ("adipose tissue", "/ˈædɪpoʊs ˈtɪʃuː/", "Connective tissue that stores energy as fat.", "脂肪组织：以脂肪形式储存能量的结缔组织。", "Adipose tissue also insulates the body.", "脂肪组织还对身体起保温作用。", 3, ["histo-"]),
        ("areolar tissue", "/əˈriːələr ˈtɪʃuː/", "A loose connective tissue that holds organs in place.", "疏松结缔组织：将器官固定在适当位置的疏松组织。", "Areolar tissue surrounds blood vessels and nerves.", "疏松结缔组织包绕血管和神经。", 5, ["histo-"]),
        ("extracellular matrix", "/ˌekstrəˈseljələr ˈmeɪtrɪks/", "The network of molecules outside cells that supports tissue.", "细胞外基质：细胞外支撑组织的分子网络。", "The extracellular matrix gives tissue its structure.", "细胞外基质赋予组织其结构。", 5, []),
        ("keratinocyte", "/kəˈrætɪnoʊsaɪt/", "The main cell type of the epidermis, producing keratin.", "角质形成细胞：表皮的主要细胞类型，产生角蛋白。", "Keratinocytes form a tough protective surface on the skin.", "角质形成细胞在皮肤表面形成坚韧的保护层。", 5, ["-cyte"]),
        ("goblet cell", "/ˈɡɒblɪt sel/", "A column-shaped cell that secretes protective mucus.", "杯状细胞：分泌保护性黏液的柱状细胞。", "Goblet cells keep the intestinal lining moist.", "杯状细胞使肠道内壁保持湿润。", 4, []),
        ("stratified epithelium", "/ˈstrætɪfaɪd ˌepɪˈθiːliəm/", "Epithelium arranged in multiple cell layers.", "复层上皮：由多层细胞排列而成的上皮。", "Stratified epithelium protects areas exposed to wear.", "复层上皮保护易受磨损的部位。", 5, []),
        ("simple epithelium", "/ˈsɪmpəl ˌepɪˈθiːliəm/", "Epithelium made of a single layer of cells.", "单层上皮：由单层细胞构成的上皮。", "Simple epithelium allows for easy absorption and diffusion.", "单层上皮便于吸收和扩散。", 4, []),
        ("endothelium", "/ˌendoʊˈθiːliəm/", "The thin epithelium lining blood vessels and the heart.", "内皮：衬于血管和心脏内表面的薄上皮。", "The endothelium controls exchange between blood and tissue.", "内皮控制血液与组织之间的物质交换。", 4, ["endo-"]),
        ("mesothelium", "/ˌmesoʊˈθiːliəm/", "The epithelium that lines body cavities such as the abdomen.", "间皮：衬于腹腔等体腔内表面的上皮。", "The mesothelium reduces friction between organs.", "间皮减少器官之间的摩擦。", 5, ["meso-"]),
        ("macrophage", "/ˈmækroʊfeɪdʒ/", "A large immune cell that engulfs pathogens and debris.", "巨噬细胞：吞噬病原体和碎屑的大型免疫细胞。", "Macrophages clear dead cells from tissues.", "巨噬细胞清除组织中的死细胞。", 4, ["macro-", "phago-"]),
        ("mast cell", "/mæst sel/", "A connective tissue cell that releases histamine in allergic responses.", "肥大细胞：在过敏反应中释放组胺的结缔组织细胞。", "Mast cells trigger inflammation when activated.", "肥大细胞被激活时引发炎症。", 4, []),
        ("plasma cell", "/ˈplæzmə sel/", "An immune cell that produces antibodies.", "浆细胞：产生抗体的免疫细胞。", "Plasma cells develop from activated B lymphocytes.", "浆细胞由活化的 B 淋巴细胞发育而来。", 4, ["-plasm"]),
        ("ground substance", "/ɡraʊnd ˈsʌbstəns/", "The gel-like material filling the space between cells and fibers.", "基质：填充于细胞与纤维间隙的凝胶状物质。", "Ground substance lets nutrients diffuse through tissue.", "基质使养分能够在组织中扩散。", 5, []),
        ("reticular fiber", "/rɪˈtɪkjələr ˈfaɪbər/", "A fine collagen fiber that forms supporting networks in organs.", "网状纤维：在器官中形成支持网络的细胶原纤维。", "Reticular fibers support the soft tissue of the spleen.", "网状纤维支持脾脏的软组织。", 5, []),
        ("pseudostratified epithelium", "/ˌsuːdoʊˈstrætɪfaɪd ˌepɪˈθiːliəm/", "Epithelium that appears layered but is a single layer.", "假复层上皮：看似分层、实为单层的上皮。", "Pseudostratified epithelium lines much of the airway.", "假复层上皮衬于大部分气道。", 5, []),
        ("melanocyte", "/məˈlænoʊsaɪt/", "A skin cell that produces the pigment melanin.", "黑素细胞：产生黑色素的皮肤细胞。", "Melanocytes give skin and hair their color.", "黑素细胞赋予皮肤和毛发颜色。", 4, ["melano-", "-cyte"]),
    ],
    # ════════════════ System 13 · Embryology / 胚胎学 ════════════════
    13: [
        ("zygote", "/ˈzaɪɡoʊt/", "The single cell formed when a sperm fertilizes an egg.", "受精卵（合子）：精子使卵子受精后形成的单个细胞。", "The zygote begins to divide soon after fertilization.", "受精卵在受精后不久即开始分裂。", 3, ["zygo-"]),
        ("gamete", "/ˈɡæmiːt/", "A reproductive cell, such as a sperm or egg.", "配子：生殖细胞，如精子或卵子。", "Gametes carry half the normal number of chromosomes.", "配子携带正常染色体数目的一半。", 3, ["gameto-"]),
        ("fertilization", "/ˌfɜːrtɪlaɪˈzeɪʃən/", "The fusion of a sperm and an egg to form a zygote.", "受精：精子与卵子融合形成受精卵。", "Fertilization usually occurs in the fallopian tube.", "受精通常发生在输卵管内。", 3, []),
        ("embryo", "/ˈembrioʊ/", "An organism in its earliest stage of development.", "胚胎：处于发育最早阶段的生物体。", "In humans, the embryo stage lasts about eight weeks.", "人类的胚胎期约持续八周。", 2, ["blasto-"]),
        ("fetus", "/ˈfiːtəs/", "An unborn offspring in the later stages of development.", "胎儿：发育后期尚未出生的后代。", "By the fetal stage all major organs have formed.", "到胎儿期，所有主要器官都已形成。", 2, []),
        ("blastocyst", "/ˈblæstoʊsɪst/", "An early embryo consisting of a hollow ball of cells.", "囊胚：由中空细胞球构成的早期胚胎。", "The blastocyst implants into the wall of the uterus.", "囊胚植入子宫壁。", 4, ["blasto-", "cysto-"]),
        ("morula", "/ˈmɔːrjələ/", "A solid ball of cells formed by early divisions of the zygote.", "桑椹胚：受精卵早期分裂形成的实心细胞球。", "The morula forms a few days after fertilization.", "桑椹胚在受精后数天形成。", 4, []),
        ("cleavage", "/ˈkliːvɪdʒ/", "The series of rapid cell divisions after fertilization.", "卵裂：受精后一系列快速的细胞分裂。", "Cleavage divides the zygote without increasing its size.", "卵裂使受精卵分裂而总体积不增大。", 4, []),
        ("implantation", "/ˌɪmplænˈteɪʃən/", "The attachment of the embryo to the wall of the uterus.", "着床：胚胎附着于子宫壁的过程。", "Implantation occurs about a week after fertilization.", "着床约在受精一周后发生。", 4, []),
        ("gastrulation", "/ˌɡæstruˈleɪʃən/", "The process that forms the three germ layers of the embryo.", "原肠胚形成：形成胚胎三个胚层的过程。", "Gastrulation rearranges cells into distinct layers.", "原肠胚形成将细胞重新排列为不同的层。", 5, []),
        ("germ layer", "/dʒɜːrm ˈleɪər/", "One of the three primary cell layers of the early embryo.", "胚层：早期胚胎三个主要细胞层之一。", "Each germ layer gives rise to specific organs.", "每个胚层发育成特定的器官。", 4, ["-derm"]),
        ("ectoderm", "/ˈektoʊdɜːrm/", "The outer germ layer that forms skin and nervous tissue.", "外胚层：形成皮肤和神经组织的外层胚层。", "The ectoderm develops into the brain and spinal cord.", "外胚层发育成脑和脊髓。", 4, ["ecto-", "-derm"]),
        ("mesoderm", "/ˈmesoʊdɜːrm/", "The middle germ layer that forms muscle, bone, and blood.", "中胚层：形成肌肉、骨骼和血液的中层胚层。", "The mesoderm gives rise to the heart and skeleton.", "中胚层发育成心脏和骨骼。", 4, ["meso-", "-derm"]),
        ("endoderm", "/ˈendoʊdɜːrm/", "The inner germ layer that forms the lining of internal organs.", "内胚层：形成内脏器官内衬的内层胚层。", "The endoderm forms the lining of the digestive tract.", "内胚层形成消化道的内衬。", 4, ["endo-", "-derm"]),
        ("differentiation", "/ˌdɪfəˌrenʃiˈeɪʃən/", "The process by which cells become specialized.", "分化：细胞变得专门化的过程。", "Differentiation turns stem cells into specific cell types.", "分化使干细胞转变为特定的细胞类型。", 4, []),
        ("stem cell", "/stem sel/", "An unspecialized cell that can develop into many cell types.", "干细胞：能发育为多种细胞类型的未分化细胞。", "Stem cells can renew themselves and differentiate.", "干细胞能够自我更新并分化。", 3, []),
        ("totipotent", "/toʊˈtɪpətənt/", "Able to develop into any cell type, including a whole organism.", "全能的：能发育为任何细胞类型乃至完整个体。", "The zygote is totipotent.", "受精卵是全能的。", 5, []),
        ("pluripotent", "/plʊˈrɪpətənt/", "Able to develop into nearly any cell type of the body.", "多能的：能发育为机体几乎任何细胞类型。", "Pluripotent stem cells can form all tissue types.", "多能干细胞可形成所有组织类型。", 5, []),
        ("organogenesis", "/ˌɔːrɡənoʊˈdʒenəsɪs/", "The formation of organs during embryonic development.", "器官发生：胚胎发育期间器官的形成。", "Organogenesis takes place mainly in the embryonic period.", "器官发生主要发生在胚胎期。", 5, ["-genesis"]),
        ("notochord", "/ˈnoʊtəkɔːrd/", "A flexible rod that defines the body axis in the early embryo.", "脊索：早期胚胎中确定身体轴线的柔韧索状结构。", "The notochord signals the formation of the neural tube.", "脊索诱导神经管的形成。", 5, []),
        ("neural tube", "/ˈnjʊərəl tjuːb/", "The embryonic structure that becomes the brain and spinal cord.", "神经管：发育为脑和脊髓的胚胎结构。", "The neural tube closes during the fourth week.", "神经管在第四周闭合。", 4, []),
        ("somite", "/ˈsoʊmaɪt/", "A block of mesoderm that forms muscle and vertebrae.", "体节：形成肌肉和椎骨的中胚层块。", "Somites appear in pairs along the embryo's axis.", "体节沿胚胎轴线成对出现。", 5, ["-some"]),
        ("placenta", "/pləˈsentə/", "The organ that supplies the fetus with nutrients and oxygen.", "胎盘：向胎儿供应养分和氧气的器官。", "The placenta connects the fetus to the uterine wall.", "胎盘将胎儿与子宫壁相连。", 3, []),
        ("umbilical cord", "/ʌmˈbɪlɪkəl kɔːrd/", "The cord that links the fetus to the placenta.", "脐带：连接胎儿与胎盘的索带。", "The umbilical cord carries blood between fetus and placenta.", "脐带在胎儿与胎盘之间输送血液。", 3, []),
        ("amnion", "/ˈæmniɒn/", "The fluid-filled membrane that surrounds and protects the embryo.", "羊膜：包绕并保护胚胎的充液膜。", "The amnion cushions the developing fetus.", "羊膜对发育中的胎儿起缓冲作用。", 5, []),
        ("chorion", "/ˈkɔːriɒn/", "The outer membrane that helps form the placenta.", "绒毛膜：协助形成胎盘的外膜。", "The chorion surrounds the amnion and embryo.", "绒毛膜包绕羊膜和胚胎。", 5, []),
        ("yolk sac", "/joʊk sæk/", "An early membrane that provides nourishment to the embryo.", "卵黄囊：为胚胎提供营养的早期膜结构。", "The yolk sac is one of the first structures to form.", "卵黄囊是最早形成的结构之一。", 5, []),
        ("trophoblast", "/ˈtrɒfoʊblæst/", "The outer cell layer of the blastocyst that forms the placenta.", "滋养层：囊胚的外层细胞，形成胎盘。", "The trophoblast helps the embryo implant in the uterus.", "滋养层帮助胚胎在子宫内着床。", 5, ["-blast"]),
        ("blastomere", "/ˈblæstoʊmɪr/", "One of the cells produced by cleavage of the zygote.", "卵裂球：受精卵卵裂产生的细胞之一。", "Each blastomere can give rise to part of the embryo.", "每个卵裂球都可发育为胚胎的一部分。", 5, ["blasto-", "-mere"]),
        ("embryogenesis", "/ˌembrioʊˈdʒenəsɪs/", "The formation and development of an embryo.", "胚胎发生：胚胎的形成与发育。", "Embryogenesis begins with the first cell division.", "胚胎发生始于第一次细胞分裂。", 5, ["blasto-", "-genesis"]),
        ("teratogen", "/ˈterətədʒən/", "An agent that causes malformations in a developing embryo.", "致畸物：导致发育中胚胎畸形的因素。", "Alcohol is a well-known teratogen.", "酒精是一种众所周知的致畸物。", 5, ["geno-"]),
        ("gestation", "/dʒeˈsteɪʃən/", "The period of development from conception to birth.", "妊娠期：从受孕到出生的发育时期。", "Human gestation lasts about forty weeks.", "人类妊娠期约为四十周。", 3, []),
        ("congenital", "/kənˈdʒenɪtəl/", "Present from birth, often describing a condition or defect.", "先天的：出生时即存在，常用于描述某种状况或缺陷。", "A congenital heart defect is present at birth.", "先天性心脏缺陷在出生时即存在。", 4, ["geno-"]),
    ],
}

# ── Micro articles ───────────────────────────────────────────────────────────
# Tuple: (system_id, title_en, title_zh, difficulty, content_en, content_zh)
MICRO_ARTICLES = [
    # ---- System 9: Cell Structure ----
    (9, "The Cell as the Unit of Life", "细胞——生命的基本单位", 1,
     "Every living thing is made of cells, the smallest units that can carry out all the processes of life. A typical human cell is bounded by a plasma membrane that controls what enters and leaves. Inside, the cytoplasm holds specialized structures called organelles, each with its own job. The nucleus stores DNA and directs the cell's activities, mitochondria supply energy, ribosomes build proteins, and the endoplasmic reticulum and Golgi apparatus process and ship those proteins. Although cells share these basic parts, they become highly specialized: a nerve cell, a muscle cell, and a red blood cell look and act very differently while following the same fundamental design.",
     "一切生物都由细胞构成，细胞是能够完成全部生命过程的最小单位。典型的人体细胞被质膜包围，质膜控制物质进出。细胞内，细胞质中含有称为细胞器的专门结构，各司其职：细胞核储存 DNA 并指挥细胞活动，线粒体供应能量，核糖体合成蛋白质，内质网和高尔基体则加工并运送这些蛋白质。尽管细胞都具备这些基本部件，它们却会高度特化——神经细胞、肌细胞和红细胞在遵循同一基本设计的同时，外形和功能却大不相同。"),
    (9, "Membranes and the Endomembrane System", "膜与内膜系统", 3,
     "The cell membrane is far more than a simple wall. It is a fluid phospholipid bilayer studded with proteins that act as channels, pumps, and receptors. This same membrane design extends inside the cell to form the endomembrane system, a connected network that includes the nuclear envelope, endoplasmic reticulum, Golgi apparatus, lysosomes, and transport vesicles. Proteins made on the rough endoplasmic reticulum are folded, modified, and passed to the Golgi apparatus for sorting, then shipped in vesicles to their destinations. Lysosomes, filled with digestive enzymes, break down worn-out parts and recycle their components. Together these compartments keep the cell's chemistry organized and efficient.",
     "细胞膜远不只是一道简单的墙。它是流动的磷脂双分子层，其中镶嵌着充当通道、泵和受体的蛋白质。这种膜结构也延伸到细胞内部，构成内膜系统——一个相互连通的网络，包括核膜、内质网、高尔基体、溶酶体和运输囊泡。在粗面内质网上合成的蛋白质经折叠、修饰后被送往高尔基体分选，再由囊泡运往目的地。充满消化酶的溶酶体则分解老化结构并回收其组分。这些区室共同使细胞的化学过程保持有序而高效。"),
    (9, "Powerhouses and Protein Factories", "能量工厂与蛋白质工厂", 2,
     "Two organelles capture the cell's essential trade-off between energy and information. Mitochondria are the powerhouses: their folded inner membranes, called cristae, host the reactions of cellular respiration that turn nutrients and oxygen into ATP, the cell's energy currency. Cells that work hard, such as muscle and liver cells, are packed with mitochondria. Ribosomes are the protein factories: these tiny machines read messenger RNA and link amino acids into chains. Some ribosomes float freely in the cytoplasm, while others attach to the endoplasmic reticulum to make proteins destined for membranes or export. Both organelles are essential, and damage to mitochondria in particular underlies many diseases.",
     "两类细胞器体现了细胞在能量与信息之间的关键权衡。线粒体是能量工厂：其折叠的内膜（称为嵴）承载细胞呼吸的反应，将养分和氧气转化为细胞的能量货币 ATP。工作繁重的细胞（如肌细胞和肝细胞）富含线粒体。核糖体则是蛋白质工厂：这些微小机器读取信使 RNA，将氨基酸连接成链。一部分核糖体游离于细胞质中，另一部分附着于内质网，合成将用于膜或输出的蛋白质。两类细胞器都不可或缺，而线粒体的损伤尤其是许多疾病的基础。"),
    (9, "The Cytoskeleton and Cell Movement", "细胞骨架与细胞运动", 3,
     "Far from being a shapeless bag, a cell is held together and moved by an internal scaffolding called the cytoskeleton. It is built from three kinds of protein fibers. Microtubules are hollow tubes that give the cell shape and serve as tracks for transporting organelles and vesicles; they also form the spindle that separates chromosomes during division. Microfilaments, made of actin, allow the cell to change shape, crawl, and pinch in two during cytokinesis. Intermediate filaments are tough, rope-like fibers that resist mechanical stress and anchor structures in place. Specialized extensions of the cytoskeleton, such as cilia and flagella, let cells sweep fluid or swim.",
     "细胞远非一只无形的口袋，而是由称为细胞骨架的内部支架支撑并驱动运动。它由三类蛋白纤维构成。微管是中空的管子，赋予细胞形状，并充当运输细胞器和囊泡的轨道；它们还形成在分裂时分离染色体的纺锤体。由肌动蛋白构成的微丝使细胞能够改变形状、爬行，并在胞质分裂时缢裂为二。中间丝是坚韧的绳索状纤维，可抵抗机械应力并将结构固定在适当位置。细胞骨架的特化延伸结构（如纤毛和鞭毛）则使细胞能够清扫液体或游动。"),
    # ---- System 10: Cell Function & Molecular ----
    (10, "Crossing the Membrane: Transport Mechanisms", "跨膜运输机制", 3,
     "The cell membrane decides what can enter and leave, and it does so by several routes. In passive transport, substances move down their concentration gradient without any energy cost: simple diffusion carries small molecules like oxygen straight through the membrane, while facilitated diffusion lets larger molecules such as glucose pass through carrier or channel proteins. Osmosis is the special case of water diffusing toward the saltier side. When a cell must move a substance against its gradient, it uses active transport, spending ATP to power protein pumps. Large items are handled in bulk: endocytosis brings material in by wrapping it in membrane, and exocytosis releases material by fusing vesicles with the membrane.",
     "细胞膜决定哪些物质可以进出，并通过多种途径实现。在被动运输中，物质顺浓度梯度移动而不消耗能量：简单扩散使氧气等小分子直接穿过膜，易化扩散则让葡萄糖等较大分子借助载体或通道蛋白通过。渗透是水向更咸一侧扩散的特例。当细胞必须逆浓度梯度运输物质时，便采用主动运输，消耗 ATP 驱动蛋白泵。大型物质则成批处理：胞吞作用用膜包裹将物质带入，胞吐作用则通过囊泡与膜融合将物质释放。"),
    (10, "Tonicity: How Cells Respond to Their Surroundings", "渗透压：细胞如何应对外环境", 2,
     "Because water crosses cell membranes freely by osmosis, the concentration of dissolved particles in the surrounding fluid has powerful effects on a cell. In an isotonic solution, the outside matches the inside, so water moves in and out equally and the cell keeps its normal shape. In a hypotonic solution, the outside is more dilute, so water rushes in and the cell swells and may even burst. In a hypertonic solution, the outside is saltier, so water leaves and the cell shrinks. This is why intravenous fluids given in hospitals are carefully matched to the body, and why both dehydration and overhydration disturb cell function.",
     "由于水可经渗透自由跨膜，周围液体中溶解颗粒的浓度对细胞有强烈影响。在等渗溶液中，外部与内部浓度相当，水进出相等，细胞保持正常形态；在低渗溶液中，外部较稀，水大量涌入，细胞肿胀甚至可能破裂；在高渗溶液中，外部较咸，水分流出，细胞皱缩。这正是医院静脉输液需与机体仔细匹配的原因，也是脱水和水中毒都会扰乱细胞功能的原因。"),
    (10, "Energy and Enzymes", "能量与酶", 3,
     "Cells run on energy, and they manage it through metabolism, the sum of all their chemical reactions. Reactions that build complex molecules, called anabolism, require energy, while reactions that break molecules down, called catabolism, release it. The energy released is captured in ATP, a molecule whose phosphate bonds store and deliver energy where it is needed. Almost every reaction in the cell is controlled by enzymes, proteins that act as catalysts. Each enzyme binds a specific substrate at its active site and lowers the energy needed for the reaction, speeding it up dramatically without being used up. By switching enzymes on and off, a cell controls when and how fast each step proceeds.",
     "细胞依靠能量运转，并通过代谢（全部化学反应的总和）来管理能量。构建复杂分子的反应称为合成代谢，需要消耗能量；分解分子的反应称为分解代谢，会释放能量。释放出的能量被 ATP 捕获——这种分子的磷酸键能够储存能量并将其输送到需要之处。细胞中几乎每个反应都由酶控制，酶是充当催化剂的蛋白质。每种酶在其活性位点结合特定底物，降低反应所需能量，从而在自身不被消耗的情况下显著加快反应。通过开启或关闭酶，细胞得以控制各步骤何时进行、进行多快。"),
    (10, "The Cell Cycle and Mitosis", "细胞周期与有丝分裂", 4,
     "To grow, repair tissue, and replace worn-out cells, the body must produce new cells through an orderly sequence called the cell cycle. Most of the cycle is spent in interphase, when the cell grows, carries out its normal work, and copies its DNA so that each new cell will receive a full set. Division of the nucleus then proceeds through mitosis in four stages: in prophase the chromosomes condense and the spindle forms; in metaphase they line up at the cell's center; in anaphase the sister chromatids are pulled to opposite poles; and in telophase two new nuclei form. Finally, cytokinesis splits the cytoplasm, yielding two genetically identical daughter cells. Loss of control over this cycle is a hallmark of cancer.",
     "为了生长、修复组织和替换老化细胞，机体必须通过称为细胞周期的有序过程产生新细胞。周期的大部分时间处于间期，此时细胞生长、执行日常功能，并复制 DNA，使每个新细胞都能获得完整的一套。随后核分裂经有丝分裂的四个阶段进行：前期染色体凝缩、纺锤体形成；中期它们排列于细胞中央；后期姐妹染色单体被拉向两极；末期形成两个新核。最后，胞质分裂将细胞质分开，产生两个遗传上完全相同的子细胞。对这一周期失去控制是癌症的标志性特征。"),
    # ---- System 11: Genetics & Molecular Biology ----
    (11, "DNA: The Molecule of Heredity", "DNA：遗传的分子", 2,
     "DNA, or deoxyribonucleic acid, is the molecule that stores the instructions for building and running a living thing. Its structure is a double helix, two strands twisted around each other like a spiral ladder. The rungs of the ladder are pairs of chemical bases, and the order of these bases spells out the genetic code. A gene is a stretch of DNA that holds the instructions for one product, usually a protein. Before a cell divides, the two strands separate and each serves as a template to build a new partner, a process called replication that ensures both daughter cells receive an identical copy. Occasional errors, or mutations, are the raw material of genetic variation and disease.",
     "DNA（脱氧核糖核酸）是储存构建和运行生命体指令的分子。它的结构为双螺旋，两条链像螺旋阶梯一样相互缠绕。阶梯的横档是成对的化学碱基，这些碱基的排列顺序拼写出遗传密码。基因是 DNA 上一段含有某一产物（通常是蛋白质）指令的序列。在细胞分裂前，两条链分开，各自作为模板合成新的配对链，这一过程称为复制，确保两个子细胞都获得完全相同的拷贝。偶尔出现的错误（即突变）是遗传变异和疾病的原始素材。"),
    (11, "From Gene to Protein", "从基因到蛋白质", 4,
     "The instructions in a gene are carried out in two steps known together as gene expression. In transcription, an enzyme reads a gene and builds a matching strand of messenger RNA, which then leaves the nucleus. In translation, ribosomes read the messenger RNA three bases at a time; each three-base codon specifies one amino acid, and transfer RNA molecules deliver the matching amino acids in order. The growing chain of amino acids folds into a polypeptide and ultimately a working protein. Because proteins do most of the cell's work — as enzymes, structures, and signals — this flow of information from DNA to RNA to protein, often called the central dogma, is fundamental to all life.",
     "基因中的指令通过合称为基因表达的两个步骤得以执行。在转录中，一种酶读取基因并合成与之匹配的信使 RNA，后者随即离开细胞核。在翻译中，核糖体每次读取信使 RNA 的三个碱基；每个三碱基密码子指定一个氨基酸，转运 RNA 分子按顺序送来相应的氨基酸。不断延长的氨基酸链折叠成多肽，最终形成有功能的蛋白质。由于蛋白质承担细胞的大部分工作——作为酶、结构和信号——这种从 DNA 到 RNA 再到蛋白质的信息流动（常称为中心法则）是一切生命的根本。"),
    (11, "Chromosomes, Alleles, and Inheritance", "染色体、等位基因与遗传", 3,
     "Genes are carried on chromosomes, the condensed packages of DNA found in the nucleus. Human body cells are diploid, holding 46 chromosomes in 23 pairs, with one member of each pair inherited from each parent. Because the pairs carry the same genes, each gene is present in two copies that may differ; these alternative forms are called alleles. A dominant allele shows its effect even when paired with a different one, while a recessive allele is expressed only when both copies match. An individual with two identical alleles is homozygous; one with two different alleles is heterozygous. These simple rules, first worked out by Gregor Mendel, explain how traits pass from one generation to the next.",
     "基因位于染色体上——染色体是细胞核中 DNA 的凝缩包装。人体体细胞为二倍体，含 46 条染色体，排成 23 对，每对中各有一条分别来自父母。由于成对染色体携带相同的基因，每个基因都以两个可能不同的拷贝存在；这些不同形式称为等位基因。显性等位基因即使与不同的等位基因配对也会表现其效应，而隐性等位基因只有在两个拷贝相同时才表达。具有两个相同等位基因的个体为纯合，具有两个不同等位基因的为杂合。这些最初由孟德尔阐明的简单规律，解释了性状如何代代相传。"),
    (11, "Mutations and Their Consequences", "突变及其后果", 4,
     "A mutation is any change in the sequence of DNA. Some arise from errors during replication, others from environmental agents such as radiation or certain chemicals. Many mutations are harmless because they fall in unused regions or do not change the resulting protein. Others alter a single amino acid and can change how a protein works — for better, for worse, or with no clear effect. When a harmful mutation occurs in a gene that controls cell division, it can contribute to cancer. Mutations in reproductive cells can be passed to offspring and cause inherited diseases such as sickle cell anemia. Yet mutation is also essential, providing the genetic variation on which evolution depends.",
     "突变是指 DNA 序列的任何改变。有些源于复制时的错误，有些则由辐射或某些化学物质等环境因素引起。许多突变是无害的，因为它们落在未被利用的区域，或并不改变所生成的蛋白质。另一些则改变单个氨基酸，可能改变蛋白质的工作方式——或好、或坏、或无明显影响。当有害突变发生在控制细胞分裂的基因中时，可能促成癌症。生殖细胞中的突变可传给后代，导致镰状细胞贫血等遗传病。然而突变也不可或缺，它提供了进化所依赖的遗传变异。"),
    # ---- System 12: Histology ----
    (12, "The Four Basic Tissue Types", "四种基本组织类型", 2,
     "Although the body contains many organs, they are all built from just four basic tissue types. Epithelial tissue covers surfaces and lines cavities and glands, forming protective barriers and controlling absorption and secretion. Connective tissue, the most varied type, supports and binds the body and includes bone, cartilage, fat, and blood. Muscle tissue is specialized to contract, producing movement, and exists as skeletal, cardiac, and smooth varieties. Nervous tissue carries electrical signals and makes up the brain, spinal cord, and nerves. By combining these four tissues in different proportions and arrangements, the body constructs every organ, from the heart to the skin.",
     "尽管人体含有众多器官，它们都由仅仅四种基本组织类型构成。上皮组织覆盖表面、衬于体腔和腺体，形成保护性屏障并控制吸收与分泌。结缔组织是种类最多的类型，支持并连接机体，包括骨、软骨、脂肪和血液。肌组织专门用于收缩以产生运动，分为骨骼肌、心肌和平滑肌。神经组织传导电信号，构成脑、脊髓和神经。通过将这四种组织以不同比例和排列加以组合，机体构建出从心脏到皮肤的每一个器官。"),
    (12, "Epithelium: Surfaces and Linings", "上皮：表面与衬里", 3,
     "Epithelial tissue forms the body's surfaces and the linings of its tubes and cavities. Its cells sit close together on a thin basement membrane that anchors them to the tissue below, and the tissue is classified by cell shape and layering. Cells may be flat (squamous), cube-shaped (cuboidal), or tall (columnar). A single layer, called simple epithelium, favors absorption and diffusion, as in the lungs and intestine; multiple layers, called stratified epithelium, protect surfaces that take wear, such as the skin and mouth. Specialized epithelial cells include goblet cells that secrete protective mucus and the endothelium that lines blood vessels. Because epithelium is constantly exposed, it renews itself rapidly throughout life.",
     "上皮组织构成机体的表面以及管道和体腔的衬里。其细胞紧密排列在薄薄的基膜上，基膜将它们固定于下层组织；该组织按细胞形状和层次分类。细胞可为扁平（鳞状）、立方（立方状）或高柱形（柱状）。单层上皮利于吸收和扩散，如肺和肠道所见；复层上皮则保护承受磨损的表面，如皮肤和口腔。特化的上皮细胞包括分泌保护性黏液的杯状细胞和衬于血管的内皮。由于上皮持续暴露，它在一生中不断快速自我更新。"),
    (12, "Connective Tissue: Support and Connection", "结缔组织：支持与连接", 3,
     "Connective tissue is the body's most abundant and diverse tissue, and unlike the others it is defined as much by what lies between its cells as by the cells themselves. Scattered cells such as fibroblasts secrete an extracellular matrix made of protein fibers and a surrounding ground substance. Collagen fibers give the matrix tensile strength, while elastin fibers let it stretch and recoil. By varying the cells and matrix, connective tissue takes many forms: loose areolar tissue cushions and connects organs, adipose tissue stores fat and insulates, and dense tissue forms tough tendons and ligaments. Even bone, cartilage, and blood are classified as connective tissues, sharing the theme of cells embedded in a specialized matrix.",
     "结缔组织是人体最丰富、最多样的组织，与其他组织不同，它的定义既取决于细胞本身，也同样取决于细胞之间的物质。成纤维细胞等散在的细胞分泌由蛋白纤维和周围基质构成的细胞外基质。胶原纤维赋予基质抗拉强度，弹性纤维则使其能伸展回弹。通过改变细胞和基质，结缔组织呈现多种形式：疏松结缔组织缓冲并连接器官，脂肪组织储存脂肪并保温，致密组织形成坚韧的肌腱和韧带。甚至骨、软骨和血液也被归为结缔组织，它们共有「细胞嵌于特化基质中」这一主题。"),
    # ---- System 13: Embryology ----
    (13, "From Fertilization to Implantation", "从受精到着床", 3,
     "Human development begins when a sperm fertilizes an egg, fusing two haploid gametes into a single diploid cell called the zygote. Over the next several days the zygote undergoes cleavage, a series of rapid divisions that increase cell number without increasing overall size, producing first a solid ball called the morula and then a hollow ball called the blastocyst. The blastocyst travels to the uterus, where its outer layer, the trophoblast, helps it embed into the uterine wall in a process called implantation. The trophoblast goes on to form part of the placenta, the organ that will nourish the embryo. These earliest events set the stage for the body plan that follows.",
     "人类发育始于精子使卵子受精，将两个单倍体配子融合为一个称为受精卵的二倍体细胞。在随后数天里，受精卵经历卵裂——一系列快速分裂使细胞数目增加而总体积不变，先形成称为桑椹胚的实心细胞球，再形成称为囊胚的中空细胞球。囊胚移行至子宫，其外层（滋养层）帮助它嵌入子宫壁，这一过程称为着床。滋养层随后形成胎盘的一部分，胎盘是将为胚胎提供营养的器官。这些最早的事件为之后的身体蓝图奠定基础。"),
    (13, "The Three Germ Layers", "三个胚层", 4,
     "Once implanted, the embryo undergoes gastrulation, a remarkable rearrangement that organizes its cells into three primary germ layers. The outer layer, the ectoderm, gives rise to the skin and the entire nervous system, including the brain and spinal cord. The middle layer, the mesoderm, forms muscle, bone, blood, the heart, and the kidneys. The inner layer, the endoderm, becomes the lining of the digestive and respiratory tracts and contributes to organs such as the liver and pancreas. From these three simple sheets, every tissue and organ of the body eventually arises. Establishing the germ layers correctly is one of the most critical steps in development.",
     "着床之后，胚胎经历原肠胚形成——一次了不起的重排，将其细胞组织成三个主要胚层。外层（外胚层）发育成皮肤和整个神经系统，包括脑和脊髓；中层（中胚层）形成肌肉、骨骼、血液、心脏和肾脏；内层（内胚层）则成为消化道和呼吸道的内衬，并参与肝、胰等器官的形成。机体的每一种组织和器官最终都由这三张简单的细胞层发育而来。正确建立胚层是发育中最关键的步骤之一。"),
    (13, "Stem Cells and Differentiation", "干细胞与分化", 4,
     "Every cell in the body descends from the single zygote, yet a neuron and a skin cell could hardly be more different. This diversity arises through differentiation, the process by which unspecialized cells switch on particular genes and take on specific roles. Early embryonic cells are remarkably flexible: the zygote is totipotent, able to form an entire organism, while slightly later cells are pluripotent, able to become nearly any cell type. As development proceeds, cells become progressively more committed until they reach their final, specialized form. Some stem cells persist into adulthood, allowing tissues such as skin, blood, and the lining of the gut to renew themselves. Understanding how differentiation is controlled is central to regenerative medicine.",
     "体内每个细胞都源自单一的受精卵，然而神经元与皮肤细胞却天差地别。这种多样性通过分化产生——分化是未特化细胞开启特定基因、承担特定角色的过程。早期胚胎细胞极为灵活：受精卵是全能的，能形成完整个体；稍后的细胞是多能的，能成为几乎任何细胞类型。随着发育推进，细胞逐渐变得更加专一，直至达到最终的特化形态。一些干细胞会保留到成年，使皮肤、血液和肠道内衬等组织得以自我更新。理解分化如何受到调控是再生医学的核心。"),
]
